import type { MerchandisingRule } from "@retailer-search/shared-types";

export interface SynonymGroup {
  terms: [string, string];
}

export interface QueryCategoryHint {
  query: string;
  department: string;
  category: string;
  subcategory?: string;
  note?: string;
}

export interface HeroDemoQuery {
  query: string;
  description: string;
  expectedHeroProductId?: string;
  facetHints?: string[];
}

/** Bidirectional synonym pairs aligned to the synthetic home-improvement catalog. */
export const DEMO_SYNONYM_GROUPS: SynonymGroup[] = [
  { terms: ["shop vac", "wet dry vacuum"] },
  { terms: ["weed eater", "string trimmer"] },
  { terms: ["breaker box", "electrical panel"] },
  { terms: ["sheetrock", "drywall"] },
  { terms: ["caulk", "sealant"] },
  { terms: ["stud finder", "stud sensor"] },
  { terms: ["outlet", "receptacle"] },
  { terms: ["gfci outlet", "ground fault outlet"] },
  { terms: ["leaf blower", "blower"] },
  { terms: ["lawn mower", "mower"] },
  { terms: ["pressure washer", "power washer"] },
  { terms: ["faucet", "tap"] },
  { terms: ["socket set", "mechanics set"] },
  { terms: ["air compressor", "compressor"] },
  { terms: ["drill driver", "cordless drill"] },
  { terms: ["impact gun", "impact wrench"] },
  { terms: ["dimmer switch", "light dimmer"] },
  { terms: ["smoke detector", "smoke alarm"] },
  { terms: ["duct tape", "utility tape"] },
  { terms: ["shop light", "utility light"] },
  { terms: ["angle grinder", "grinder"] },
  { terms: ["extension cord", "power cord"] },
  { terms: ["ac unit", "air conditioner"] },
  { terms: ["impact driver", "impact drill"] },
  { terms: ["paint sprayer", "spray gun"] },
  { terms: ["drywall screws", "sheetrock screws"] },
  { terms: ["ceiling fan", "overhead fan"] },
  { terms: ["primer", "sealer primer"] },
  { terms: ["toilet flange", "closet flange"] },
  { terms: ["table saw", "bench saw"] },
  { terms: ["miter saw", "chop saw"] },
  { terms: ["romex", "nm-b wire"] },
  { terms: ["pvc pipe", "plastic pipe"] },
  { terms: ["hvac filter", "furnace filter"] },
  { terms: ["pull down faucet", "pull-down faucet"] },
  { terms: ["led bulb", "led light bulb"] },
  { terms: ["water heater", "hot water heater"] },
  { terms: ["smart thermostat", "wifi thermostat"] },
];

export const DEMO_TYPO_CORRECTIONS: Record<string, string> = {
  dril: "drill",
  "cieling fan": "ceiling fan",
  "ceilng fan": "ceiling fan",
  "water heeter": "water heater",
  "extenstion cord": "extension cord",
  "extention cord": "extension cord",
  "pain sprayer": "paint sprayer",
  "paint spryer": "paint sprayer",
  hammr: "hammer",
  mulsh: "mulch",
  mulhc: "mulch",
  plierss: "pliers",
  recepatcle: "receptacle",
  drywal: "drywall",
  shopvac: "shop vac",
  "shop vav": "shop vac",
  "presure washer": "pressure washer",
  "weed eatr": "weed eater",
  "drywll screws": "drywall screws",
  "smoke detecter": "smoke detector",
  "cordles drill": "cordless drill",
  lawnmover: "lawn mower",
  "gfic outlet": "gfci outlet",
  "impct driver": "impact driver",
  "mitre saw": "miter saw",
  thermastat: "smart thermostat",
  "led shop ligt": "led shop light",
  "sheetrock mud": "drywall compound",
  "leaf blowr": "leaf blower",
};

export const DEMO_ZERO_RESULT_FALLBACKS: Record<string, string> = {
  "hose bib": "outdoor faucet",
  "sheet rock mud": "drywall compound",
  "weed whip": "string trimmer",
  "breaker panel box": "electrical panel",
  "ceiling light round flush": "flush mount light",
  "garage organizer wall": "wall storage rack",
  "wall patch kit": "drywall repair kit",
  "deck stain sealer": "exterior wood stain",
  "bug sprayer yard": "pump sprayer",
  "weed eater line": "trimmer line",
  "outlet cover plate": "wall plate",
  "breaker switch": "circuit breaker",
  "wood putty stick": "wood filler",
  "pipe dope": "thread sealant",
  "outdoor plug cover": "weatherproof outlet cover",
  "garage wall hook": "storage hook",
  "sheetrock tape": "drywall tape",
  "hot water tank": "water heater",
  "grass trimmer": "string trimmer",
  "bathroom sink sprayer": "pull-down faucet",
};

export const DEMO_QUERY_CATEGORY_HINTS: QueryCategoryHint[] = [
  { query: "drywall screws", department: "Hardware", category: "Fasteners", subcategory: "Screws" },
  { query: "gfci outlet", department: "Electrical", category: "Outlets", subcategory: "GFCI Outlets" },
  { query: "weed eater", department: "Outdoor Power Equipment", category: "Trimmers", subcategory: "String Trimmers" },
  { query: "faucet", department: "Plumbing", category: "Kitchen Faucets", subcategory: "Pull-Down Faucets" },
  { query: "ceiling fan", department: "Lighting & Ceiling Fans", category: "Ceiling Fans", subcategory: "Indoor Fans" },
  { query: "shop vac", department: "Power Tools", category: "Vacuums", subcategory: "Shop Vacuums" },
  { query: "cordless drill", department: "Power Tools", category: "Drills", subcategory: "Cordless Drills" },
  { query: "pressure washer", department: "Outdoor Power Equipment", category: "Pressure Washers", subcategory: "Gas Pressure Washers" },
  { query: "mulch", department: "Lawn & Garden", category: "Mulch & Soil", subcategory: "Mulch" },
  { query: "miter saw", department: "Power Tools", category: "Saws", subcategory: "Circular Saws" },
  { query: "led shop light", department: "Lighting & Ceiling Fans", category: "Work Lighting", subcategory: "Shop Lights" },
  { query: "smart thermostat", department: "Smart Home", category: "Climate", subcategory: "Thermostats" },
  { query: "water heater", department: "Heating, Venting & Cooling", category: "Water Heaters", subcategory: "Tank Water Heaters" },
  { query: "storage shelving", department: "Storage & Organization", category: "Garage Storage", subcategory: "Wall Racks" },
  { query: "interior paint", department: "Paint", category: "Interior Paint", subcategory: "Wall Paint" },
  { query: "leaf blower", department: "Outdoor Power Equipment", category: "Blowers", subcategory: "Leaf Blowers" },
  { query: "paint sprayer", department: "Paint", category: "Sprayers", subcategory: "Paint Sprayers" },
  { query: "breaker box", department: "Electrical", category: "Panels", subcategory: "Load Centers" },
];

export const DEMO_HERO_QUERIES: HeroDemoQuery[] = [
  { query: "cordless drill", description: "Power-tool staple with drill/driver combos and contractor kits.", expectedHeroProductId: "prod-hero-001", facetHints: ["brand", "category", "inStock"] },
  { query: "impact driver", description: "Compact high-torque drivers for decking and framing.", expectedHeroProductId: "prod-hero-002", facetHints: ["brand", "inStock"] },
  { query: "shop vac", description: "Wet/dry vacuums for garage cleanup and workshop dust.", expectedHeroProductId: "prod-hero-003", facetHints: ["brand", "category"] },
  { query: "ceiling fan", description: "Indoor and damp-rated fans with light kits.", expectedHeroProductId: "prod-hero-009", facetHints: ["brand", "inStock"] },
  { query: "gfci outlet", description: "Tamper-resistant GFCI receptacles for kitchen and bath.", expectedHeroProductId: "prod-hero-008", facetHints: ["brand", "inStock"] },
  { query: "pressure washer", description: "Gas and electric pressure washers for siding and driveways.", expectedHeroProductId: "prod-hero-018", facetHints: ["brand", "category"] },
  { query: "weed eater", description: "String trimmers for lawn edging and weed control.", expectedHeroProductId: "prod-hero-021", facetHints: ["brand", "inStock"] },
  { query: "drywall screws", description: "Coarse-thread screws for hanging gypsum board.", expectedHeroProductId: "prod-hero-006", facetHints: ["brand", "inStock"] },
  { query: "interior paint", description: "Low-VOC wall paints in multiple sheens and sizes.", expectedHeroProductId: "prod-hero-010", facetHints: ["brand", "category"] },
  { query: "mulch", description: "Hardwood and color-enhanced landscape mulch bags.", expectedHeroProductId: "prod-hero-017", facetHints: ["brand", "inStock"] },
  { query: "bathroom faucet", description: "Single-handle bath faucets and widespread sets.", expectedHeroProductId: "prod-hero-012", facetHints: ["brand", "inStock"] },
  { query: "smart thermostat", description: "Wi-Fi thermostats with app control and room sensors.", expectedHeroProductId: "prod-hero-023", facetHints: ["brand", "category"] },
  { query: "miter saw", description: "Sliding and compound miter saws for trim work.", expectedHeroProductId: "prod-hero-026", facetHints: ["brand", "inStock"] },
  { query: "led shop light", description: "Linkable LED fixtures for garages and workshops.", expectedHeroProductId: "prod-hero-013", facetHints: ["brand", "inStock"] },
  { query: "water heater", description: "Tank and tankless water heaters for residential use.", expectedHeroProductId: "prod-hero-031", facetHints: ["brand", "category"] },
  { query: "paint sprayer", description: "HVLP and airless sprayers for interior and exterior paint.", expectedHeroProductId: "prod-hero-041", facetHints: ["brand", "inStock"] },
  { query: "leaf blower", description: "Battery and gas blowers for yard cleanup.", expectedHeroProductId: "prod-hero-032", facetHints: ["brand", "inStock"] },
  { query: "storage shelving", description: "Boltless shelving and wall-mounted garage storage.", expectedHeroProductId: "prod-hero-049", facetHints: ["brand", "category"] },
];

export function buildSynonymMap(): Record<string, string> {
  const map: Record<string, string> = {};
  for (const group of DEMO_SYNONYM_GROUPS) {
    const [left, right] = group.terms;
    map[left] = right;
    map[right] = left;
  }
  return map;
}

export function buildDemoMerchandisingRules(): MerchandisingRule[] {
  return [
    {
      id: "rule-demo-pin-cordless-drill",
      name: "Pin hero cordless drill combo for cordless drill searches",
      active: true,
      priority: 120,
      action: "pin",
      condition: { query: "cordless drill" },
      productIds: ["prod-hero-001"],
    },
    {
      id: "rule-demo-pin-impact-driver",
      name: "Pin brushless impact driver for impact driver searches",
      active: true,
      priority: 118,
      action: "pin",
      condition: { query: "impact driver" },
      productIds: ["prod-hero-002"],
    },
    {
      id: "rule-demo-boost-instock-drills",
      name: "Boost in-stock drills for drill searches",
      active: true,
      priority: 110,
      action: "boost",
      condition: { query: "drill", inStock: true },
      boostAmount: 35,
    },
    {
      id: "rule-demo-boost-contractor-drills",
      name: "Boost contractor-grade cordless drills for pro queries",
      active: true,
      priority: 108,
      action: "boost",
      condition: { query: "contractor drill" },
      brand: "RidgeLine Tools",
      boostAmount: 30,
    },
    {
      id: "rule-demo-bury-oos-mulch",
      name: "Bury out-of-stock mulch for mulch searches",
      active: true,
      priority: 105,
      action: "bury",
      condition: { query: "mulch", inStock: false },
      buryAmount: 40,
    },
    {
      id: "rule-demo-boost-seasonal-mulch",
      name: "Promote spring mulch assortment",
      active: true,
      priority: 103,
      action: "boost",
      condition: { query: "mulch", category: "Lawn & Garden" },
      boostAmount: 28,
    },
    {
      id: "rule-demo-boost-contractor-miter-saw",
      name: "Boost contractor-grade miter saws",
      active: true,
      priority: 100,
      action: "boost",
      condition: { query: "miter saw" },
      brand: "ProSaw Industrial",
      boostAmount: 30,
    },
    {
      id: "rule-demo-boost-seasonal-lawn",
      name: "Boost seasonal lawn products for mower searches",
      active: true,
      priority: 95,
      action: "boost",
      condition: { query: "mower", category: "Outdoor Power Equipment" },
      boostAmount: 25,
    },
    {
      id: "rule-demo-boost-ceiling-fan",
      name: "Boost ceiling fan category for fan searches",
      active: true,
      priority: 90,
      action: "boost",
      condition: { query: "ceiling fan", category: "Lighting & Ceiling Fans" },
      boostAmount: 28,
    },
    {
      id: "rule-demo-bury-oos-shop-vac",
      name: "Bury out-of-stock shop vacs",
      active: true,
      priority: 88,
      action: "bury",
      condition: { query: "shop vac", inStock: false },
      buryAmount: 35,
    },
    {
      id: "rule-demo-pin-shop-vac",
      name: "Pin hero wet/dry shop vac",
      active: true,
      priority: 87,
      action: "pin",
      condition: { query: "wet dry vacuum" },
      productIds: ["prod-hero-003"],
    },
    {
      id: "rule-demo-boost-gfci",
      name: "Boost GFCI outlet pack for outlet searches",
      active: true,
      priority: 85,
      action: "boost",
      condition: { query: "gfci" },
      productIds: ["prod-hero-008"],
      boostAmount: 32,
    },
    {
      id: "rule-demo-pin-pressure-washer",
      name: "Pin hero gas pressure washer",
      active: true,
      priority: 82,
      action: "pin",
      condition: { query: "pressure washer" },
      productIds: ["prod-hero-018"],
    },
    {
      id: "rule-demo-bury-oos-pressure-washer",
      name: "Reduce out-of-stock pressure washer visibility",
      active: true,
      priority: 81,
      action: "bury",
      condition: { query: "pressure washer", inStock: false },
      buryAmount: 38,
    },
    {
      id: "rule-demo-boost-string-trimmer",
      name: "Boost string trimmer for weed eater searches",
      active: true,
      priority: 80,
      action: "boost",
      condition: { query: "weed", category: "Outdoor Power Equipment" },
      boostAmount: 22,
    },
    {
      id: "rule-demo-boost-leaf-blower",
      name: "Boost leaf blowers for blower searches",
      active: true,
      priority: 79,
      action: "boost",
      condition: { query: "leaf blower" },
      productIds: ["prod-hero-032"],
      boostAmount: 26,
    },
    {
      id: "rule-demo-boost-drywall-screws",
      name: "Boost drywall screws in fastener searches",
      active: true,
      priority: 78,
      action: "boost",
      condition: { query: "drywall screws" },
      boostAmount: 24,
    },
    {
      id: "rule-demo-boost-sheetrock",
      name: "Improve sheetrock-related query recovery via drywall boost",
      active: true,
      priority: 77,
      action: "boost",
      condition: { query: "sheetrock" },
      productIds: ["prod-hero-025"],
      boostAmount: 22,
    },
    {
      id: "rule-demo-boost-interior-paint",
      name: "Boost interior paint hero for wall paint searches",
      active: true,
      priority: 76,
      action: "boost",
      condition: { query: "interior paint" },
      productIds: ["prod-hero-010"],
      boostAmount: 24,
    },
    {
      id: "rule-demo-boost-paint-sprayer",
      name: "Boost paint sprayer for spray gun searches",
      active: true,
      priority: 75,
      action: "boost",
      condition: { query: "paint sprayer" },
      productIds: ["prod-hero-041"],
      boostAmount: 28,
    },
    {
      id: "rule-demo-boost-bathroom-faucet",
      name: "Boost bathroom faucet for faucet searches",
      active: true,
      priority: 74,
      action: "boost",
      condition: { query: "bathroom faucet" },
      productIds: ["prod-hero-012"],
      boostAmount: 25,
    },
    {
      id: "rule-demo-boost-smart-thermostat",
      name: "Promote high-efficiency smart thermostats",
      active: true,
      priority: 73,
      action: "boost",
      condition: { query: "smart thermostat" },
      productIds: ["prod-hero-023", "prod-hero-050"],
      boostAmount: 30,
    },
    {
      id: "rule-demo-boost-led-shop-light",
      name: "Boost LED shop lights for garage lighting searches",
      active: true,
      priority: 72,
      action: "boost",
      condition: { query: "led shop light" },
      productIds: ["prod-hero-013"],
      boostAmount: 26,
    },
    {
      id: "rule-demo-boost-water-heater",
      name: "Boost tank water heaters for water heater searches",
      active: true,
      priority: 71,
      action: "boost",
      condition: { query: "water heater" },
      productIds: ["prod-hero-031"],
      boostAmount: 24,
    },
    {
      id: "rule-demo-boost-storage-shelving",
      name: "Boost garage shelving for storage searches",
      active: true,
      priority: 70,
      action: "boost",
      condition: { query: "storage shelving" },
      productIds: ["prod-hero-049"],
      boostAmount: 22,
    },
    {
      id: "rule-demo-boost-budget-drill",
      name: "Boost value drill kits for budget drill searches",
      active: true,
      priority: 68,
      action: "boost",
      condition: { query: "budget drill" },
      brand: "ProGrade Tools",
      boostAmount: 18,
    },
    {
      id: "rule-demo-boost-primer",
      name: "Boost primer hero for primer searches",
      active: true,
      priority: 66,
      action: "boost",
      condition: { query: "primer" },
      productIds: ["prod-hero-011"],
      boostAmount: 26,
    },
    {
      id: "rule-demo-boost-smoke-detector",
      name: "Boost smoke detector pack",
      active: true,
      priority: 65,
      action: "boost",
      condition: { query: "smoke detector" },
      productIds: ["prod-hero-020"],
      boostAmount: 30,
    },
    {
      id: "rule-demo-boost-extension-cord",
      name: "Boost outdoor extension cords",
      active: true,
      priority: 60,
      action: "boost",
      condition: { query: "extension cord", category: "Electrical" },
      boostAmount: 20,
    },
    {
      id: "rule-demo-boost-summit-electric",
      name: "Boost Summit Electric for electrical panel searches",
      active: true,
      priority: 58,
      action: "boost",
      condition: { query: "breaker box" },
      brand: "Summit Electric",
      boostAmount: 22,
    },
    {
      id: "rule-demo-hide-oos-fans",
      name: "Hide out-of-stock ceiling fans",
      active: true,
      priority: 55,
      action: "hide",
      condition: { query: "ceiling fan", inStock: false },
    },
    {
      id: "rule-demo-bury-clearance-paint",
      name: "Bury premium paint on clearance paint searches",
      active: true,
      priority: 52,
      action: "bury",
      condition: { query: "clearance paint" },
      buryAmount: 20,
    },
    {
      id: "rule-demo-default-instock-boost",
      name: "Default in-stock boost",
      active: true,
      priority: 10,
      action: "boost",
      condition: { inStock: true },
      boostAmount: 5,
    },
    {
      id: "rule-demo-bury-oos-default",
      name: "Bury out-of-stock items by default",
      active: true,
      priority: 5,
      action: "bury",
      condition: { inStock: false },
      buryAmount: 15,
    },
  ];
}

export function getDemoRuleCounts(): Record<string, number> {
  return {
    synonymGroups: DEMO_SYNONYM_GROUPS.length,
    typoCorrections: Object.keys(DEMO_TYPO_CORRECTIONS).length,
    merchandisingRules: buildDemoMerchandisingRules().length,
    zeroResultFallbacks: Object.keys(DEMO_ZERO_RESULT_FALLBACKS).length,
    queryCategoryHints: DEMO_QUERY_CATEGORY_HINTS.length,
    heroQueries: DEMO_HERO_QUERIES.length,
  };
}
