/* Auto-generated by prisma/seed.ts — do not edit manually. */
import { readFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import type { ProductDocument } from "@retailer-search/shared-types";

const catalogPath = join(dirname(fileURLToPath(import.meta.url)), "../prisma/seed-data/generated/catalog.json");
const catalog = JSON.parse(readFileSync(catalogPath, "utf8")) as { products: ProductDocument[] };

export const seedProducts: ProductDocument[] = catalog.products;
