import type { ProductDocument } from "@retailer-search/shared-types";

const timestamp = new Date().toISOString();

export const seedProducts: ProductDocument[] = [
  {
    id: "prod-001",
    sku: "SKU-HAMMER-16",
    title: "16oz Steel Claw Hammer",
    brand: "BuildRight",
    category: "Tools",
    subcategory: "Hand Tools",
    description: "Durable steel claw hammer with ergonomic rubber grip.",
    price: 24.99,
    inventory: 48,
    inStock: true,
    attributes: { weight: "16oz", material: "steel", color: "blue" },
    createdAt: timestamp,
    updatedAt: timestamp,
  },
  {
    id: "prod-002",
    sku: "SKU-MILK-2GAL",
    title: "Whole Milk 1 Gallon",
    brand: "FreshFarm",
    category: "Dairy",
    subcategory: "Milk",
    description: "Farm-fresh whole milk, vitamin D fortified.",
    price: 4.29,
    inventory: 120,
    inStock: true,
    attributes: { size: "1 gallon", organic: false },
    createdAt: timestamp,
    updatedAt: timestamp,
  },
  {
    id: "prod-003",
    sku: "SKU-MILK-ORG",
    title: "Organic Whole Milk 1 Gallon",
    brand: "Green Valley",
    category: "Dairy",
    subcategory: "Milk",
    description: "USDA organic whole milk from pasture-raised cows.",
    price: 6.49,
    inventory: 64,
    inStock: true,
    attributes: { size: "1 gallon", organic: true },
    createdAt: timestamp,
    updatedAt: timestamp,
  },
  {
    id: "prod-004",
    sku: "SKU-CEREAL-FLAKES",
    title: "Corn Flakes Cereal 18oz",
    brand: "Kellogg's",
    category: "Grocery",
    subcategory: "Breakfast",
    description: "Classic crispy corn flakes for a quick breakfast.",
    price: 3.99,
    inventory: 90,
    inStock: true,
    attributes: { size: "18oz", vegetarian: true },
    createdAt: timestamp,
    updatedAt: timestamp,
  },
  {
    id: "prod-005",
    sku: "SKU-CEREAL-OAT",
    title: "Honey Nut Oat Clusters 14oz",
    brand: "General Mills",
    category: "Grocery",
    subcategory: "Breakfast",
    description: "Sweet oat clusters with honey and almond flavor.",
    price: 4.49,
    inventory: 72,
    inStock: true,
    attributes: { size: "14oz", vegetarian: true },
    createdAt: timestamp,
    updatedAt: timestamp,
  },
  {
    id: "prod-006",
    sku: "SKU-PASTA-PENNE",
    title: "Penne Rigate Pasta 16oz",
    brand: "Barilla",
    category: "Grocery",
    subcategory: "Pantry",
    description: "Italian durum wheat penne for everyday meals.",
    price: 1.79,
    inventory: 150,
    inStock: true,
    attributes: { size: "16oz", vegetarian: true },
    createdAt: timestamp,
    updatedAt: timestamp,
  },
  {
    id: "prod-007",
    sku: "SKU-SALSA-MED",
    title: "Medium Chunky Salsa 24oz",
    brand: "FreshFarm",
    category: "Grocery",
    subcategory: "Condiments",
    description: "Tomato salsa with mild heat and chunky vegetables.",
    price: 3.49,
    inventory: 55,
    inStock: true,
    attributes: { size: "24oz", spiceLevel: "medium", vegetarian: true },
    createdAt: timestamp,
    updatedAt: timestamp,
  },
  {
    id: "prod-008",
    sku: "SKU-SALSA-HOT",
    title: "Hot Habanero Salsa 16oz",
    brand: "FreshFarm",
    category: "Grocery",
    subcategory: "Condiments",
    description: "Fiery habanero salsa for heat lovers.",
    price: 3.99,
    inventory: 0,
    inStock: false,
    attributes: { size: "16oz", spiceLevel: "hot", vegetarian: true },
    createdAt: timestamp,
    updatedAt: timestamp,
  },
  {
    id: "prod-009",
    sku: "SKU-TOWEL-6PK",
    title: "Paper Towels 6 Pack",
    brand: "Tide",
    category: "Household",
    subcategory: "Paper Goods",
    description: "Absorbent 2-ply paper towels for kitchen cleanup.",
    price: 9.99,
    inventory: 80,
    inStock: true,
    attributes: { size: "6 pack", color: "white" },
    createdAt: timestamp,
    updatedAt: timestamp,
  },
  {
    id: "prod-010",
    sku: "SKU-BLEACH-96",
    title: "Concentrated Bleach 96oz",
    brand: "Clorox",
    category: "Household",
    subcategory: "Cleaning",
    description: "Disinfecting bleach for laundry and surfaces.",
    price: 5.49,
    inventory: 40,
    inStock: true,
    attributes: { size: "96oz" },
    createdAt: timestamp,
    updatedAt: timestamp,
  },
  {
    id: "prod-011",
    sku: "SKU-COLA-12PK",
    title: "Cola Soda 12 Pack",
    brand: "Nestlé",
    category: "Beverages",
    subcategory: "Soda",
    description: "Classic cola in 12 oz cans, 12 pack.",
    price: 7.99,
    inventory: 100,
    inStock: true,
    attributes: { size: "12 pack" },
    createdAt: timestamp,
    updatedAt: timestamp,
  },
  {
    id: "prod-012",
    sku: "SKU-WATER-24PK",
    title: "Spring Water 24 Pack",
    brand: "Green Valley",
    category: "Beverages",
    subcategory: "Water",
    description: "Purified spring water bottles, 16.9 oz each.",
    price: 4.99,
    inventory: 200,
    inStock: true,
    attributes: { size: "24 pack", organic: false },
    createdAt: timestamp,
    updatedAt: timestamp,
  },
  {
    id: "prod-013",
    sku: "SKU-CHIPS-BBQ",
    title: "BBQ Potato Chips 10oz",
    brand: "Kellogg's",
    category: "Snacks",
    subcategory: "Chips",
    description: "Kettle-cooked chips with smoky barbecue seasoning.",
    price: 3.29,
    inventory: 65,
    inStock: true,
    attributes: { size: "10oz", vegetarian: true },
    createdAt: timestamp,
    updatedAt: timestamp,
  },
  {
    id: "prod-014",
    sku: "SKU-NUTS-MIX",
    title: "Trail Mix Variety Pack",
    brand: "General Mills",
    category: "Snacks",
    subcategory: "Nuts",
    description: "Almonds, cashews, and dried fruit snack mix.",
    price: 8.49,
    inventory: 35,
    inStock: true,
    attributes: { size: "12oz", vegetarian: true, organic: false },
    createdAt: timestamp,
    updatedAt: timestamp,
  },
  {
    id: "prod-015",
    sku: "SKU-APPLE-3LB",
    title: "Honeycrisp Apples 3lb Bag",
    brand: "FreshFarm",
    category: "Produce",
    subcategory: "Fruit",
    description: "Crisp sweet apples perfect for snacking.",
    price: 5.99,
    inventory: 45,
    inStock: true,
    attributes: { size: "3lb", organic: false },
    createdAt: timestamp,
    updatedAt: timestamp,
  },
  {
    id: "prod-016",
    sku: "SKU-SPINACH-ORG",
    title: "Organic Baby Spinach 10oz",
    brand: "Green Valley",
    category: "Produce",
    subcategory: "Vegetables",
    description: "Pre-washed organic baby spinach leaves.",
    price: 4.49,
    inventory: 28,
    inStock: true,
    attributes: { size: "10oz", organic: true, vegetarian: true },
    createdAt: timestamp,
    updatedAt: timestamp,
  },
  {
    id: "prod-017",
    sku: "SKU-DRILL-18V",
    title: "18V Cordless Drill Kit",
    brand: "BuildRight",
    category: "Tools",
    subcategory: "Power Tools",
    description: "Compact drill driver with battery and charger.",
    price: 89.99,
    inventory: 18,
    inStock: true,
    attributes: { color: "black", material: "steel" },
    createdAt: timestamp,
    updatedAt: timestamp,
  },
  {
    id: "prod-018",
    sku: "SKU-PAINT-1GAL",
    title: "Interior Eggshell Paint 1 Gallon",
    brand: "BuildRight",
    category: "Tools",
    subcategory: "Paint",
    description: "Low-VOC washable paint for living spaces.",
    price: 34.99,
    inventory: 0,
    inStock: false,
    attributes: { size: "1 gallon", color: "ivory" },
    createdAt: timestamp,
    updatedAt: timestamp,
  },
  {
    id: "prod-019",
    sku: "SKU-CHEESE-CHED",
    title: "Sharp Cheddar Block 8oz",
    brand: "Kraft",
    category: "Dairy",
    subcategory: "Cheese",
    description: "Aged sharp cheddar for sandwiches and cooking.",
    price: 3.79,
    inventory: 58,
    inStock: true,
    attributes: { size: "8oz", vegetarian: true },
    createdAt: timestamp,
    updatedAt: timestamp,
  },
  {
    id: "prod-020",
    sku: "SKU-YOGURT-GREEK",
    title: "Greek Yogurt Plain 32oz",
    brand: "Kraft",
    category: "Dairy",
    subcategory: "Yogurt",
    description: "Thick protein-rich plain Greek yogurt.",
    price: 5.29,
    inventory: 42,
    inStock: true,
    attributes: { size: "32oz", vegetarian: true },
    createdAt: timestamp,
    updatedAt: timestamp,
  },
  {
    id: "prod-021",
    sku: "SKU-RICE-5LB",
    title: "Long Grain White Rice 5lb",
    brand: "Barilla",
    category: "Grocery",
    subcategory: "Pantry",
    description: "Versatile long grain rice for everyday meals.",
    price: 6.99,
    inventory: 88,
    inStock: true,
    attributes: { size: "5lb", vegetarian: true },
    createdAt: timestamp,
    updatedAt: timestamp,
  },
  {
    id: "prod-022",
    sku: "SKU-SOAP-LIQ",
    title: "Lavender Hand Soap 12oz",
    brand: "Clorox",
    category: "Household",
    subcategory: "Personal Care",
    description: "Gentle liquid hand soap with lavender scent.",
    price: 2.99,
    inventory: 95,
    inStock: true,
    attributes: { size: "12oz", color: "purple" },
    createdAt: timestamp,
    updatedAt: timestamp,
  },
];
