import { mkdirSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { PrismaClient } from "@prisma/client";
import { DEMO_PASSWORD, DEMO_USERS } from "./seed-data/demo-users.js";
import { HOME_IMPROVEMENT_TAXONOMY } from "./seed-data/home-improvement-taxonomy.js";
import { SYNTHETIC_BRANDS } from "./seed-data/brands.js";
import {
  buildDemoMerchandisingRules,
  buildSynonymMap,
  DEMO_TYPO_CORRECTIONS,
  DEMO_ZERO_RESULT_FALLBACKS,
} from "./seed-data/search-rules.js";
import {
  generateProductCatalog,
  summarizeCatalog,
  TARGET_PRODUCT_COUNT,
} from "./seed-utils/product-generator.js";
import { buildWorkflowSeedBundle } from "./seed-utils/workflow-generator.js";
import { DEMO_RNG_SEED } from "./seed-utils/random.js";

const prisma = new PrismaClient();
const seedDir = dirname(fileURLToPath(import.meta.url));
const apiRoot = join(seedDir, "..");

async function clearDemoData(): Promise<void> {
  await prisma.webhookDeliveryLog.deleteMany({
    where: { id: { startsWith: "webhook-delivery-demo-" } },
  });
  await prisma.webhookEndpoint.deleteMany({
    where: { id: { startsWith: "webhook-demo-" } },
  });
  await prisma.exportJob.deleteMany({ where: { id: { startsWith: "export-demo-" } } });
  await prisma.collaborationAnnotation.deleteMany({
    where: { id: { startsWith: "annotation-demo-" } },
  });
  await prisma.collaborationComment.deleteMany({
    where: { id: { startsWith: "comment-demo-" } },
  });
  await prisma.notification.deleteMany({ where: { id: { startsWith: "notif-demo-" } } });
  await prisma.jitElevationRequest.deleteMany({ where: { id: { startsWith: "jit-demo-" } } });
  await prisma.accessReviewItem.deleteMany({ where: { runId: { startsWith: "access-review-demo-" } } });
  await prisma.accessReviewRun.deleteMany({ where: { id: { startsWith: "access-review-demo-" } } });
  await prisma.approvalRequest.deleteMany({ where: { id: { startsWith: "approval-demo-" } } });
  await prisma.auditTrailEntry.deleteMany({ where: { id: { startsWith: "audit-demo-" } } });
  await prisma.systemConfig.deleteMany({ where: { key: { startsWith: "demo." } } });
}

async function seedUsers(): Promise<void> {
  for (const user of DEMO_USERS) {
    await prisma.user.upsert({
      where: { id: user.id },
      create: {
        id: user.id,
        email: user.email,
        name: user.name,
        role: user.role,
        active: true,
        password: DEMO_PASSWORD,
      },
      update: {
        email: user.email,
        name: user.name,
        role: user.role,
        active: true,
        password: DEMO_PASSWORD,
      },
    });
  }
}

function writeCatalogArtifacts(products: ReturnType<typeof generateProductCatalog>["products"]): void {
  const generatedDir = join(seedDir, "seed-data", "generated");
  mkdirSync(generatedDir, { recursive: true });

  const catalogPath = join(generatedDir, "catalog.json");
  writeFileSync(
    catalogPath,
    JSON.stringify(
      {
        generatedAt: "2026-03-15T12:00:00.000Z",
        seed: DEMO_RNG_SEED,
        targetCount: TARGET_PRODUCT_COUNT,
        products,
      },
      null,
      2,
    ),
    "utf8",
  );

  const seedProductsPath = join(apiRoot, "src", "seed-products.ts");
  writeFileSync(
    seedProductsPath,
    `/* Auto-generated by prisma/seed.ts — do not edit manually. */\nimport type { ProductDocument } from "@retailer-search/shared-types";\nimport catalog from "../prisma/seed-data/generated/catalog.json" assert { type: "json" };\n\nexport const seedProducts: ProductDocument[] = catalog.products as ProductDocument[];\n`,
    "utf8",
  );
}

async function seedSystemConfig(
  catalog: ReturnType<typeof generateProductCatalog>,
  workflow: ReturnType<typeof buildWorkflowSeedBundle>,
): Promise<void> {
  const synonymMap = buildSynonymMap();
  const merchandisingRules = buildDemoMerchandisingRules();
  const entries: Array<{ key: string; value: unknown }> = [
    { key: "demo.catalog.meta", value: summarizeCatalog(catalog) },
    { key: "demo.catalog.products", value: catalog.products },
    { key: "demo.taxonomy.leaves", value: HOME_IMPROVEMENT_TAXONOMY },
    { key: "demo.brands", value: SYNTHETIC_BRANDS },
    { key: "demo.search.synonyms.staging", value: synonymMap },
    { key: "demo.search.synonyms.live", value: synonymMap },
    { key: "demo.search.rules.staging", value: merchandisingRules },
    { key: "demo.search.rules.live", value: merchandisingRules },
    { key: "demo.search.typoMap", value: DEMO_TYPO_CORRECTIONS },
    { key: "demo.search.zeroResultFallbacks", value: DEMO_ZERO_RESULT_FALLBACKS },
    { key: "demo.experiments", value: workflow.experiments },
  ];

  for (const entry of entries) {
    await prisma.systemConfig.upsert({
      where: { key: entry.key },
      create: { key: entry.key, value: entry.value as object },
      update: { value: entry.value as object },
    });
  }
}

async function seedWorkflow(workflow: ReturnType<typeof buildWorkflowSeedBundle>): Promise<void> {
  await prisma.approvalRequest.createMany({ data: workflow.approvals, skipDuplicates: true });
  for (const review of workflow.accessReviews) {
    await prisma.accessReviewRun.create({ data: review.run });
    await prisma.accessReviewItem.createMany({ data: review.items, skipDuplicates: true });
  }
  await prisma.jitElevationRequest.createMany({ data: workflow.jitRequests, skipDuplicates: true });
  await prisma.notification.createMany({ data: workflow.notifications, skipDuplicates: true });
  await prisma.collaborationComment.createMany({ data: workflow.comments, skipDuplicates: true });
  await prisma.collaborationAnnotation.createMany({ data: workflow.annotations, skipDuplicates: true });
  await prisma.auditTrailEntry.createMany({ data: workflow.auditEntries, skipDuplicates: true });
  await prisma.webhookEndpoint.createMany({ data: workflow.webhooks, skipDuplicates: true });
  for (const delivery of workflow.webhookDeliveries) {
    await prisma.webhookDeliveryLog.create({ data: delivery });
  }
  await prisma.exportJob.createMany({ data: workflow.exportJobs, skipDuplicates: true });
}

async function markDemoBootstrapComplete(): Promise<void> {
  await prisma.bootstrapState.upsert({
    where: { id: "default" },
    create: {
      id: "default",
      status: "completed",
      initializedAt: new Date("2026-03-15T12:00:00.000Z"),
      initializedByUserId: "user-admin",
      initializedByEmail: "admin@example.com",
      instanceName: "Retail Discovery Platform Demo",
      firstAdminEmail: "admin@example.com",
      securityDefaultsApplied: true,
      governanceDefaultsApplied: true,
    },
    update: {
      status: "completed",
      initializedAt: new Date("2026-03-15T12:00:00.000Z"),
      initializedByUserId: "user-admin",
      initializedByEmail: "admin@example.com",
      instanceName: "Retail Discovery Platform Demo",
      firstAdminEmail: "admin@example.com",
      securityDefaultsApplied: true,
      governanceDefaultsApplied: true,
    },
  });
}

async function main(): Promise<void> {
  console.log(`Seeding synthetic home improvement demo data (seed=${DEMO_RNG_SEED})...`);

  await clearDemoData();
  await seedUsers();

  const catalog = generateProductCatalog(DEMO_RNG_SEED);
  if (catalog.products.length !== TARGET_PRODUCT_COUNT) {
    throw new Error(`Expected ${TARGET_PRODUCT_COUNT} products, got ${catalog.products.length}`);
  }

  writeCatalogArtifacts(catalog.products);
  const workflow = buildWorkflowSeedBundle(catalog.products, DEMO_RNG_SEED);

  await seedSystemConfig(catalog, workflow);
  await seedWorkflow(workflow);
  await markDemoBootstrapComplete();

  const counts = {
    users: DEMO_USERS.length,
    products: catalog.products.length,
    heroProducts: catalog.heroCount,
    variantProducts: catalog.variantProductCount,
    simpleProducts: catalog.simpleProductCount,
    leafCategories: HOME_IMPROVEMENT_TAXONOMY.length,
    brands: SYNTHETIC_BRANDS.length,
    approvals: workflow.approvals.length,
    accessReviewRuns: workflow.accessReviews.length,
    jitRequests: workflow.jitRequests.length,
    notifications: workflow.notifications.length,
    comments: workflow.comments.length,
    annotations: workflow.annotations.length,
    auditEntries: workflow.auditEntries.length,
    webhooks: workflow.webhooks.length,
    webhookDeliveries: workflow.webhookDeliveries.length,
    exportJobs: workflow.exportJobs.length,
    experiments: workflow.experiments.experiments.length,
    experimentRuns: workflow.experiments.runs.length,
    synonymGroups: 25,
    typoCorrections: Object.keys(DEMO_TYPO_CORRECTIONS).length,
    merchandisingRules: buildDemoMerchandisingRules().length,
    zeroResultFallbacks: Object.keys(DEMO_ZERO_RESULT_FALLBACKS).length,
  };

  console.log("Demo seed completed.");
  console.log(JSON.stringify(counts, null, 2));
}

main()
  .catch((error: unknown) => {
    console.error("Seed failed:", error);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
