import type { HeroProductTemplate, VariantFamilyTemplate } from "./product-templates.js";

/** Curated Fleet Farm-style hero SKUs modeled on FleetFarm.com departments and product types. */
export const FLEET_FARM_HERO_TEMPLATES: HeroProductTemplate[] = [
  {
    id: "ff-hero-001",
    leafId: "leaf-ff-rifle-scopes",
    brand: "Vortex",
    title: "Vortex Crossfire II 3-9x40 Riflescope",
    shortDescription: "Versatile 3-9x40 hunting scope with fully multi-coated lenses and fast-focus eyepiece.",
    longDescription:
      "The Vortex Crossfire II 3-9x40 delivers clear images in low light with a dead-hold BDC reticle ideal for whitetail and varmint hunting. Waterproof, fogproof, and shockproof construction stands up to Midwest field conditions. A popular pick in Fleet Farm Hunting & Shooting optics for deer season.",
    price: 149.99,
    inventory: 42,
    inventoryStatus: "in_stock",
    keywords: ["rifle scope", "vortex scope", "3-9x40", "hunting optics", "deer hunting"],
    specs: { magnification: "3-9x", objectiveLens: "40 mm", reticle: "Dead-Hold BDC", tubeSize: "1 in" },
    isSeasonal: true,
    popularityScore: 94,
  },
  {
    id: "ff-hero-002",
    leafId: "leaf-ff-game-cameras",
    brand: "Browning Trail Cameras",
    title: "Browning Strike Force Pro X 20MP Trail Camera",
    shortDescription: "20MP trail camera with 80 ft detection range and adjustable IR flash.",
    longDescription:
      "Scout deer movement before opener with the Browning Strike Force Pro X. Records 20MP stills and 1600x900 video with a 0.22-second trigger. Fleet Farm hunters rely on it for food plots, fence lines, and public-land scouting across Wisconsin and Minnesota.",
    price: 119.99,
    inventory: 36,
    inventoryStatus: "in_stock",
    keywords: ["trail camera", "game camera", "deer camera", "browning camera"],
    specs: { megapixels: 20, detectionRange: "80 ft", flashType: "infrared", batteryCount: 6 },
    isSeasonal: true,
    popularityScore: 91,
  },
  {
    id: "ff-hero-003",
    leafId: "leaf-ff-fishing-rods",
    brand: "Shimano",
    title: "Shimano FX Spinning Rod 6 ft 6 in Medium",
    shortDescription: "Durable fiberglass spinning rod for walleye, panfish, and bass.",
    longDescription:
      "The Shimano FX spinning rod pairs with most 2500-series reels for Great Lakes tributaries and local lakes. Reinforced aluminum oxide guides and a comfortable EVA grip make it a Fleet Farm fishing aisle staple for opener weekend.",
    price: 24.99,
    inventory: 88,
    inventoryStatus: "in_stock",
    keywords: ["spinning rod", "fishing rod", "shimano rod", "walleye rod"],
    specs: { length: "6 ft 6 in", power: "medium", pieces: 2, material: "fiberglass" },
    isSeasonal: true,
    popularityScore: 86,
  },
  {
    id: "ff-hero-004",
    leafId: "leaf-ff-fishing-reels",
    brand: "Shimano",
    title: "Shimano Sienna 2500 FG Spinning Reel",
    shortDescription: "Smooth front-drag spinning reel with Super Stopper II anti-reverse.",
    longDescription:
      "Lightweight graphite body with 4+1 ball bearings handles mono and braid for multispecies fishing. A top seller in Fleet Farm Fishing reels for dock fishing, river walleye, and family camping trips.",
    price: 39.99,
    inventory: 64,
    inventoryStatus: "in_stock",
    keywords: ["spinning reel", "shimano reel", "fishing reel"],
    specs: { size: "2500", bearings: "4+1", maxDrag: "10 lb", gearRatio: "5.0:1" },
    isSeasonal: true,
    popularityScore: 88,
  },
  {
    id: "ff-hero-005",
    leafId: "leaf-ff-dog-food",
    brand: "Purina",
    title: "Purina Pro Plan Sport 30/20 Salmon & Rice Formula 35 lb",
    shortDescription: "High-protein performance dog food for active sporting breeds.",
    longDescription:
      "Purina Pro Plan Sport 30/20 fuels hunting dogs and farm companions with 30% protein and 20% fat. Real salmon is the first ingredient. Fleet Farm pet shoppers choose this bag for upland season, training, and year-round working dogs.",
    price: 54.99,
    inventory: 120,
    inventoryStatus: "in_stock",
    keywords: ["dog food", "purina pro plan", "sporting dog food", "high protein dog food"],
    specs: { bagWeight: "35 lb", protein: "30%", fat: "20%", flavor: "salmon and rice" },
    popularityScore: 90,
  },
  {
    id: "ff-hero-006",
    leafId: "leaf-ff-wild-bird-seed",
    brand: "Red Lake",
    title: "Red Lake Premium Wild Bird Seed Mix 20 lb",
    shortDescription: "No-waste blend with sunflower hearts for backyard feeders.",
    longDescription:
      "Attract cardinals, chickadees, and finches with Red Lake premium mix formulated for Upper Midwest winters. Low shell debris keeps patios clean. One of Fleet Farm's most repurchased wild bird items.",
    price: 19.99,
    inventory: 210,
    inventoryStatus: "in_stock",
    keywords: ["bird seed", "wild bird seed", "red lake bird seed", "sunflower hearts"],
    specs: { bagWeight: "20 lb", seedType: "no-waste mix", season: "year-round" },
    isSeasonal: true,
    popularityScore: 92,
  },
  {
    id: "ff-hero-007",
    leafId: "leaf-ff-cattle-feed",
    brand: "Nutrena",
    title: "Nutrena Stockers 14% Textured Cattle Feed 50 lb",
    shortDescription: "14% protein textured feed for growing cattle on pasture.",
    longDescription:
      "Balanced energy and minerals support rate of gain for stocker cattle. Palatable molasses coating improves intake. Trusted by Fleet Farm farm & livestock customers for backgrounding calves through fall.",
    price: 22.99,
    inventory: 180,
    inventoryStatus: "in_stock",
    keywords: ["cattle feed", "stock feed", "nutrena cattle", "livestock feed"],
    specs: { protein: "14%", bagWeight: "50 lb", form: "textured", species: "cattle" },
    isContractorGrade: true,
    popularityScore: 87,
  },
  {
    id: "ff-hero-008",
    leafId: "leaf-ff-poultry-feed",
    brand: "Blue Seal",
    title: "Blue Seal Home Fresh Extra Egg Layer Pellets 50 lb",
    shortDescription: "Complete layer feed for consistent egg production.",
    longDescription:
      "Fortified with calcium and marigold extract for strong shells and rich yolks. Ideal for backyard flocks and small farm operations shopping Fleet Farm poultry nutrition.",
    price: 21.49,
    inventory: 145,
    inventoryStatus: "in_stock",
    keywords: ["chicken feed", "layer pellets", "poultry feed", "egg layer feed"],
    specs: { protein: "16%", bagWeight: "50 lb", form: "pellets", species: "poultry" },
    popularityScore: 89,
  },
  {
    id: "ff-hero-009",
    leafId: "leaf-ff-motor-oil",
    brand: "Mobil 1",
    title: "Mobil 1 Advanced Full Synthetic Motor Oil 5W-30 5 qt",
    shortDescription: "Full synthetic 5W-30 oil for extended engine protection.",
    longDescription:
      "Protects in extreme cold starts common across the Upper Midwest. Meets dexos1 Gen 2 specifications for modern trucks and SUVs. Fleet Farm auto maintenance shoppers pair this with filters for DIY oil changes.",
    price: 28.99,
    inventory: 96,
    inventoryStatus: "in_stock",
    keywords: ["motor oil", "synthetic oil", "5w30", "mobil 1"],
    specs: { viscosity: "5W-30", containerSize: "5 qt", synthetic: true, apiRating: "SN Plus" },
    popularityScore: 93,
  },
  {
    id: "ff-hero-010",
    leafId: "leaf-ff-farm-batteries",
    brand: "Interstate Batteries",
    title: "Interstate Farm & Truck Battery Group 65",
    shortDescription: "Heavy-duty flooded battery for farm trucks and work vehicles.",
    longDescription:
      "High cold-cranking amps for diesel pickups and plow trucks. Free battery testing available at Fleet Farm Auto Service Centers. A go-to replacement for rural commuters and ranch pickups.",
    price: 159.99,
    inventory: 28,
    inventoryStatus: "in_stock",
    keywords: ["truck battery", "farm battery", "interstate battery", "group 65"],
    specs: { groupSize: "65", cca: 850, warranty: "30 month", terminal: "top post" },
    isContractorGrade: true,
    popularityScore: 85,
  },
  {
    id: "ff-hero-011",
    leafId: "leaf-ff-carhartt-jacket",
    brand: "Carhartt",
    title: "Carhartt Loose Fit Midweight Hooded Sweatshirt",
    shortDescription: "Classic Carhartt hoodie with handwarmer pocket and triple-stitched seams.",
    longDescription:
      "Soft cotton blend fleece stands up to barn chores and jobsite wear. Available in signature Carhartt colors throughout Fleet Farm Clothing & Footwear. Layer-friendly fit works from September goose season through spring calving.",
    price: 59.99,
    inventory: 74,
    inventoryStatus: "in_stock",
    keywords: ["carhartt hoodie", "work sweatshirt", "carhartt jacket", "workwear"],
    specs: { fit: "loose", weight: "midweight", hooded: true, material: "cotton blend fleece" },
    isSeasonal: true,
    popularityScore: 96,
  },
  {
    id: "ff-hero-012",
    leafId: "leaf-ff-work-boots",
    brand: "Wolverine",
    title: "Wolverine Overpass 6 in Composite Toe Work Boot",
    shortDescription: "Waterproof composite-toe boot with cushioned footbed.",
    longDescription:
      "Electrical hazard protection and oil/slip-resistant outsole for shop and construction floors. Fleet Farm footwear specialists recommend it for all-day comfort on concrete and muddy feedlots.",
    price: 139.99,
    inventory: 41,
    inventoryStatus: "in_stock",
    keywords: ["work boots", "composite toe boots", "wolverine boots", "waterproof work boots"],
    specs: { height: "6 in", toeType: "composite", waterproof: true, ehRated: true },
    isContractorGrade: true,
    popularityScore: 88,
  },
  {
    id: "ff-hero-013",
    leafId: "leaf-ff-yeti-cooler",
    brand: "Yeti",
    title: "YETI Tundra 45 Hard Cooler",
    shortDescription: "Rotomolded cooler with Permafrost insulation and bear-resistant latches.",
    longDescription:
      "Keeps ice for days on fishing trips, tailgates, and camp weekends. Fits in most truck beds with non-slip feet. A premium Fleet Farm Sporting Goods pick for hunters and lake anglers.",
    price: 325.0,
    inventory: 18,
    inventoryStatus: "in_stock",
    keywords: ["yeti cooler", "tundra 45", "hard cooler", "rotomolded cooler"],
    specs: { capacity: "26 cans", insulation: "Permafrost", bearResistant: true, weight: "23 lb" },
    isSeasonal: true,
    popularityScore: 90,
  },
  {
    id: "ff-hero-014",
    leafId: "leaf-ff-chainsaw",
    brand: "Husqvarna",
    title: "Husqvarna 455 Rancher 20 in Gas Chainsaw",
    shortDescription: "55.5 cc ranch chainsaw with X-Torq engine and LowVib system.",
    longDescription:
      "Cut firewood and clear storm damage with a 20 in bar and tool-less chain tensioning. Fleet Farm outdoor power customers pair it with chaps, helmets, and bar oil for safe woodlot work.",
    price: 429.99,
    inventory: 14,
    inventoryStatus: "low_stock",
    keywords: ["chainsaw", "husqvarna chainsaw", "gas chainsaw", "rancher chainsaw"],
    specs: { engineSize: "55.5 cc", barLength: "20 in", fuelType: "gas", xTorq: true },
    isSeasonal: true,
    isContractorGrade: true,
    popularityScore: 87,
  },
  {
    id: "ff-hero-015",
    leafId: "leaf-ff-snow-blower",
    brand: "Toro",
    title: "Toro Power Max HD 828 OAE Two-Stage Snow Blower",
    shortDescription: "28 in two-stage snow blower with Auto-Orient chute and electric start.",
    longDescription:
      "Commercial-grade gearbox and 14 in auger height throw snow up to 50 ft for long driveways. Fleet Farm seasonal power equipment teams stock this model before Upper Midwest winter storms.",
    price: 1299.99,
    inventory: 8,
    inventoryStatus: "low_stock",
    keywords: ["snow blower", "two stage snow blower", "toro snow blower"],
    specs: { clearingWidth: "28 in", stages: 2, engine: "252 cc", electricStart: true },
    isSeasonal: true,
    popularityScore: 84,
  },
  {
    id: "ff-hero-016",
    leafId: "leaf-ff-livestock-fencing",
    brand: "Behlen",
    title: "Behlen Country 2 Joule AC Powered Fence Charger",
    shortDescription: "Low-impedance charger for up to 50 miles of multi-wire fence.",
    longDescription:
      "Keeps cattle and horses contained on pasture with consistent pulse output. Weather-resistant housing mounts in barns or utility sheds. Standard Fleet Farm farm fencing solution for rotational grazing.",
    price: 189.99,
    inventory: 22,
    inventoryStatus: "in_stock",
    keywords: ["electric fence charger", "fence energizer", "livestock fencing"],
    specs: { output: "2 joule", power: "AC", range: "50 miles", lowImpedance: true },
    isContractorGrade: true,
    popularityScore: 82,
  },
  {
    id: "ff-hero-017",
    leafId: "leaf-ff-snacks",
    brand: "Jack Link's",
    title: "Jack Link's Original Beef Jerky Family Size 10 oz",
    shortDescription: "Smoked beef jerky snack pack for road trips and camp coolers.",
    longDescription:
      "High-protein jerky stocked near Fleet Farm checkout lanes and camping aisles. Resealable bag keeps snacks fresh on hunting weekends and youth sports travel across the Midwest.",
    price: 12.99,
    inventory: 200,
    inventoryStatus: "in_stock",
    keywords: ["beef jerky", "jack links", "meat snacks", "protein snack"],
    specs: { weight: "10 oz", flavor: "original", protein: "9 g per serving" },
    popularityScore: 83,
  },
  {
    id: "ff-hero-018",
    leafId: "leaf-ff-deer-attractant",
    brand: "Red Lake",
    title: "Red Lake Deer Block Apple Mineral Attractant 20 lb",
    shortDescription: "Long-lasting mineral block with apple flavor for trail monitoring.",
    longDescription:
      "Place near game cameras or stand locations to pattern deer before season. Weather-resistant formula for northern climates. Popular Fleet Farm hunting accessory in late summer and early fall.",
    price: 14.99,
    inventory: 156,
    inventoryStatus: "in_stock",
    keywords: ["deer attractant", "mineral block", "deer block", "food plot"],
    specs: { weight: "20 lb", flavor: "apple", type: "mineral block", species: "whitetail" },
    isSeasonal: true,
    popularityScore: 86,
  },
  {
    id: "ff-hero-019",
    leafId: "leaf-ff-trailer-hitches",
    brand: "Reese",
    title: "Reese Class III Trailer Hitch Kit",
    shortDescription: "Custom-fit trailer hitch with 2 in receiver for midsize trucks and SUVs.",
    longDescription:
      "Rated for 5,000 lb gross trailer weight with bolt-on installation on popular farm trucks. Fleet Farm towing department helps match ball mounts and wiring kits for boat and utility trailers.",
    price: 219.99,
    inventory: 19,
    inventoryStatus: "in_stock",
    keywords: ["trailer hitch", "reese hitch", "class 3 hitch", "towing"],
    specs: { class: "III", receiverSize: "2 in", gtwr: "5000 lb", finish: "black powder coat" },
    isContractorGrade: true,
    popularityScore: 80,
  },
  {
    id: "ff-hero-020",
    leafId: "leaf-ff-tackle-boxes",
    brand: "Plano",
    title: "Plano 3700 Deep StowAway Tackle Box",
    shortDescription: "Adjustable dividers and secure latches for organized tackle storage.",
    longDescription:
      "Translucent lids make it easy to find jigs and crankbaits on early-morning launches. Fits in standard boat compartments. Fleet Farm fishing department endcap favorite for gift season.",
    price: 14.99,
    inventory: 112,
    inventoryStatus: "in_stock",
    keywords: ["tackle box", "plano tackle", "fishing storage"],
    specs: { compartments: 4, depth: "deep", material: "polypropylene", waterproofLatch: true },
    isSeasonal: true,
    popularityScore: 78,
  },
  {
    id: "ff-hero-021",
    leafId: "leaf-cordless-drills",
    brand: "DeWalt",
    title: "DEWALT 20V MAX Cordless Drill/Driver Kit",
    shortDescription: "Brushless drill/driver kit with two batteries for shop and barn projects.",
    longDescription:
      "Compact drill handles everything from gate hardware to deck screws. Part of Fleet Farm Tools & Hardware power tool wall alongside Milwaukee and Ryobi platforms.",
    price: 199.0,
    inventory: 55,
    inventoryStatus: "in_stock",
    keywords: ["dewalt drill", "cordless drill", "20v drill", "drill driver kit"],
    specs: { voltage: "20V MAX", chuckSize: "1/2 in", brushless: true, includedBatteries: 2 },
    isContractorGrade: true,
    popularityScore: 95,
  },
  {
    id: "ff-hero-022",
    leafId: "leaf-ff-ice-melt",
    brand: "Fleet Farm",
    title: "Fleet Farm Ice Melt Blend 50 lb Bag",
    shortDescription: "Fast-acting ice melt pellets safe for concrete walkways and barn aprons.",
    longDescription:
      "Exclusive Fleet Farm winter maintenance blend works below 0°F for store entrances, feedlot alleys, and home sidewalks. Stock up before first freeze across Wisconsin and Minnesota.",
    price: 16.99,
    inventory: 320,
    inventoryStatus: "in_stock",
    keywords: ["ice melt", "rock salt", "snow melt", "fleet farm ice melt"],
    specs: { bagWeight: "50 lb", form: "pellets", tempRating: "-15°F", surfaceSafe: "concrete" },
    isSeasonal: true,
    popularityScore: 91,
  },
  {
    id: "ff-hero-023",
    leafId: "leaf-ff-heated-water",
    brand: "Fleet Farm",
    title: "Fleet Farm 5 Gallon Heated Livestock Bucket",
    shortDescription: "Thermostatically controlled bucket prevents freezing in barns and paddocks.",
    longDescription:
      "Keeps water available for horses and cattle during January cold snaps. Hidden heating element resists chewing and abrasion. Essential Fleet Farm livestock winter care product.",
    price: 54.99,
    inventory: 48,
    inventoryStatus: "in_stock",
    keywords: ["heated bucket", "livestock water", "horse bucket", "winter watering"],
    specs: { capacity: "5 gal", thermostat: true, cordLength: "6 ft", wattage: 260 },
    isSeasonal: true,
    isContractorGrade: true,
    popularityScore: 84,
  },
  {
    id: "ff-hero-024",
    leafId: "leaf-ff-shooting-safety",
    brand: "Howard Leight",
    title: "Howard Leight Impact Sport Electronic Earmuffs",
    shortDescription: "Electronic hearing protection amplifies range commands while blocking gunshot noise.",
    longDescription:
      "Low-profile cups fit under hunting caps and integrate with archery range practice. Fleet Farm shooting sports customers use them for indoor ranges and sight-in days before deer camp.",
    price: 49.99,
    inventory: 67,
    inventoryStatus: "in_stock",
    keywords: ["shooting earmuffs", "electronic ear protection", "howard leight"],
    specs: { nrr: "22 dB", electronic: true, folding: true, batteryPowered: true },
    isSeasonal: true,
    popularityScore: 81,
  },
  {
    id: "ff-hero-025",
    leafId: "leaf-mulch",
    brand: "Fleet Farm",
    title: "Fleet Farm Premium Hardwood Mulch 2 cu ft",
    shortDescription: "Shredded hardwood mulch for landscape beds and tree rings.",
    longDescription:
      "Natural brown mulch suppresses weeds and retains soil moisture for spring landscaping projects. Pallet quantities available at Fleet Farm stores with exterior yard space.",
    price: 4.49,
    inventory: 480,
    inventoryStatus: "in_stock",
    keywords: ["mulch", "hardwood mulch", "landscape mulch", "fleet farm mulch"],
    specs: { bagSize: "2 cu ft", material: "hardwood", color: "natural brown" },
    isSeasonal: true,
    popularityScore: 90,
  },
];

export const FLEET_FARM_VARIANT_FAMILIES: VariantFamilyTemplate[] = [
  {
    id: "ff-family-dog-food",
    leafId: "leaf-ff-dog-food",
    brand: "Purina",
    baseTitle: "Purina Dog Chow Complete",
    description: "Complete adult dog nutrition for everyday feeding.",
    keywords: ["dog food", "purina dog chow"],
    variants: [
      { suffix: "18 lb Bag", specs: { bagWeight: "18 lb" }, priceMultiplier: 1, inventoryWeight: 3 },
      { suffix: "32 lb Bag", specs: { bagWeight: "32 lb" }, priceMultiplier: 1.6, inventoryWeight: 2 },
      { suffix: "44 lb Bag", specs: { bagWeight: "44 lb" }, priceMultiplier: 2.1, inventoryWeight: 2 },
    ],
  },
  {
    id: "ff-family-motor-oil",
    leafId: "leaf-ff-motor-oil",
    brand: "Mobil 1",
    baseTitle: "Mobil 1 Advanced Full Synthetic Motor Oil",
    description: "Full synthetic motor oil for cars, trucks, and farm equipment.",
    keywords: ["motor oil", "synthetic oil"],
    variants: [
      { suffix: "5W-30 1 qt", specs: { viscosity: "5W-30", containerSize: "1 qt" }, priceMultiplier: 0.35, inventoryWeight: 4 },
      { suffix: "5W-30 5 qt", specs: { viscosity: "5W-30", containerSize: "5 qt" }, priceMultiplier: 1, inventoryWeight: 3 },
      { suffix: "10W-30 5 qt", specs: { viscosity: "10W-30", containerSize: "5 qt" }, priceMultiplier: 1, inventoryWeight: 2 },
    ],
  },
];

export const FLEET_FARM_LEAF_KEYWORDS: Record<string, string[]> = {
  "leaf-ff-rifle-scopes": ["rifle scope", "hunting scope", "vortex", "optics"],
  "leaf-ff-game-cameras": ["trail camera", "game camera", "cellular camera"],
  "leaf-ff-fishing-rods": ["fishing rod", "spinning rod", "casting rod"],
  "leaf-ff-fishing-reels": ["spinning reel", "baitcast reel", "fishing reel"],
  "leaf-ff-dog-food": ["dog food", "dry dog food", "puppy food"],
  "leaf-ff-wild-bird-seed": ["bird seed", "wild bird feed", "sunflower seed"],
  "leaf-ff-cattle-feed": ["cattle feed", "stock feed", "mineral"],
  "leaf-ff-poultry-feed": ["chicken feed", "layer feed", "poultry"],
  "leaf-ff-motor-oil": ["motor oil", "synthetic oil", "oil change"],
  "leaf-ff-farm-batteries": ["car battery", "truck battery", "farm battery"],
  "leaf-ff-carhartt-jacket": ["carhartt", "work jacket", "hoodie"],
  "leaf-ff-work-boots": ["work boots", "steel toe boots", "wolverine"],
  "leaf-ff-yeti-cooler": ["yeti cooler", "hard cooler", "camping cooler"],
  "leaf-ff-chainsaw": ["chainsaw", "husqvarna", "chainsaw bar oil"],
  "leaf-ff-snow-blower": ["snow blower", "snow thrower", "toro snow"],
  "leaf-ff-snacks": ["beef jerky", "snacks", "jack links"],
  "leaf-ff-livestock-fencing": ["electric fence", "fence charger", "pasture fence"],
  "leaf-ff-trailer-hitches": ["trailer hitch", "tow hitch", "reese hitch"],
  "leaf-ff-ice-melt": ["ice melt", "salt", "snow ice melt"],
  "leaf-ff-heated-water": ["heated bucket", "livestock waterer", "horse water"],
};
