export interface HeroProductTemplate {
  id: string;
  leafId: string;
  brand: string;
  title: string;
  shortDescription: string;
  longDescription: string;
  price: number;
  compareAtPrice?: number;
  inventory: number;
  inventoryStatus: "in_stock" | "low_stock" | "out_of_stock";
  keywords: string[];
  specs: Record<string, string | number | boolean>;
  isContractorGrade?: boolean;
  isSeasonal?: boolean;
  popularityScore: number;
}

export interface VariantFamilyTemplate {
  id: string;
  leafId: string;
  brand: string;
  baseTitle: string;
  description: string;
  variants: Array<{
    suffix: string;
    specs: Record<string, string | number | boolean>;
    priceMultiplier: number;
    inventoryWeight: number;
  }>;
  keywords: string[];
}

export const HERO_PRODUCT_TEMPLATES: HeroProductTemplate[] = [
  { id: "prod-hero-001", leafId: "leaf-cordless-drills", brand: "RidgeLine Tools", title: "RidgeLine 20V Cordless Drill/Driver Combo Kit", shortDescription: "Contractor-ready 20V drill/driver combo with two batteries and charger.", longDescription: "The RidgeLine 20V Cordless Drill/Driver Combo Kit includes a brushless drill, impact-ready clutch, two 2.0Ah batteries, and a fast charger.", price: 179.99, compareAtPrice: 219.99, inventory: 84, inventoryStatus: "in_stock", keywords: ["cordless drill", "drill combo", "20v drill"], specs: { voltage: "20V", batteryPlatform: "RidgeLine 20V", toolType: "Drill/Driver", chuckSize: "1/2 in", cordless: true, includedBatteries: 2 }, isContractorGrade: true, popularityScore: 98 },
  { id: "prod-hero-002", leafId: "leaf-impact-drivers", brand: "TorqueLine Drivers", title: "TorqueLine 20V Brushless Impact Driver", shortDescription: "Compact impact driver with high torque for deck and framing work.", longDescription: "Deliver high torque in tight spaces with the TorqueLine brushless impact driver and LED ring.", price: 129.99, inventory: 62, inventoryStatus: "in_stock", keywords: ["impact driver", "cordless impact"], specs: { voltage: "20V", toolType: "Impact Driver", cordless: true, includedBatteries: 1 }, isContractorGrade: true, popularityScore: 91 },
  { id: "prod-hero-003", leafId: "leaf-shop-vacs", brand: "IronPeak", title: "IronPeak 12-Gallon Wet/Dry Shop Vacuum", shortDescription: "12-gallon shop vac with blower port and auto-start outlet.", longDescription: "Tackle garage cleanup, wet spills, and workshop dust with a 12-gallon tank and reusable filter.", price: 119.99, inventory: 47, inventoryStatus: "in_stock", keywords: ["shop vac", "wet dry vacuum"], specs: { voltage: "120V", tankCapacity: "12 gal", toolType: "Wet/Dry Vac" }, popularityScore: 88 },
  { id: "prod-hero-004", leafId: "leaf-hammers", brand: "BlueForge", title: "BlueForge 16 oz Rip Claw Hammer", shortDescription: "Forged steel rip claw hammer with shock-absorb grip.", longDescription: "Balanced 16 oz head with rip claw and textured grip for demolition and carpentry.", price: 19.99, inventory: 210, inventoryStatus: "in_stock", keywords: ["hammer", "claw hammer"], specs: { headWeight: "16 oz", handleMaterial: "fiberglass" }, popularityScore: 76 },
  { id: "prod-hero-005", leafId: "leaf-socket-sets", brand: "PrecisionMechanic", title: "PrecisionMechanic 120-Piece Mechanics Tool Set", shortDescription: "Metric and SAE socket set with ratchet and extensions.", longDescription: "Chrome vanadium sockets and organized carry case for automotive work.", price: 89.99, inventory: 38, inventoryStatus: "low_stock", keywords: ["socket set", "mechanics set"], specs: { pieceCount: 120, driveSize: "1/4 & 3/8 in" }, isContractorGrade: true, popularityScore: 82 },
  { id: "prod-hero-006", leafId: "leaf-fasteners", brand: "DrywallDirect", title: "DrywallDirect #6 x 1-1/4 in Drywall Screws 5 lb", shortDescription: "Phosphate-coated coarse-thread drywall screws.", longDescription: "5 lb bucket of coarse-thread screws for hanging drywall to wood studs.", price: 24.99, inventory: 156, inventoryStatus: "in_stock", keywords: ["drywall screws", "sheetrock screws"], specs: { size: "#6 x 1-1/4 in", weight: "5 lb" }, isContractorGrade: true, popularityScore: 85 },
  { id: "prod-hero-007", leafId: "leaf-dimension-lumber", brand: "StudPro Lumber", title: "StudPro Pressure-Treated 2 in x 4 in x 8 ft Lumber", shortDescription: "Pressure-treated southern yellow pine stud.", longDescription: "Ideal for outdoor framing and ground-contact projects.", price: 7.98, inventory: 420, inventoryStatus: "in_stock", keywords: ["2x4", "pressure treated lumber"], specs: { nominalDimensions: "2 in x 4 in", length: "8 ft", pressureTreated: true }, isContractorGrade: true, popularityScore: 90 },
  { id: "prod-hero-008", leafId: "leaf-gfci-outlets", brand: "Summit Electric", title: "Summit Electric GFCI Outlet 3-Pack", shortDescription: "Tamper-resistant GFCI outlets for kitchen and bath.", longDescription: "15A 125V tamper-resistant GFCI receptacles with LED indicator.", price: 39.99, compareAtPrice: 47.99, inventory: 95, inventoryStatus: "in_stock", keywords: ["gfci outlet", "ground fault outlet"], specs: { amperage: "15A", packCount: 3 }, popularityScore: 87 },
  { id: "prod-hero-009", leafId: "leaf-ceiling-fans", brand: "FanCraft Air", title: "FanCraft 52 in Brushed Nickel Ceiling Fan with Light", shortDescription: "52 in indoor ceiling fan with dimmable LED light kit.", longDescription: "Reversible motor, remote control, and quiet operation for living spaces.", price: 149.99, inventory: 33, inventoryStatus: "in_stock", keywords: ["ceiling fan", "52 inch fan"], specs: { bladeSpan: "52 in", finish: "brushed nickel", dampRated: true }, popularityScore: 92 },
  { id: "prod-hero-010", leafId: "leaf-interior-paint", brand: "TrueCoat Paints", title: "TrueCoat UltraHide Interior Paint 5 gal", shortDescription: "Low-VOC interior paint with one-coat hide in Soft White.", longDescription: "Scrubbable acrylic latex for living rooms, bedrooms, and hallways.", price: 128.99, inventory: 41, inventoryStatus: "in_stock", keywords: ["interior paint", "5 gallon paint"], specs: { sheen: "Eggshell", containerSize: "5 gal", interiorExterior: "interior" }, popularityScore: 89 },
  { id: "prod-hero-011", leafId: "leaf-primer", brand: "FreshCoat Studio", title: "FreshCoat Multi-Surface Primer 1 gal", shortDescription: "Stain-blocking primer for drywall, wood, and patched walls.", longDescription: "Fast-dry primer seals porous surfaces before topcoats.", price: 24.99, inventory: 118, inventoryStatus: "in_stock", keywords: ["primer", "drywall primer"], specs: { containerSize: "1 gal", interiorExterior: "interior" }, popularityScore: 80 },
  { id: "prod-hero-012", leafId: "leaf-kitchen-faucets", brand: "StoneMill Home", title: "StoneMill Pull-Down Kitchen Faucet in Matte Black", shortDescription: "Single-handle pull-down faucet with spot-resistant finish.", longDescription: "Magnetic docking spray head and ceramic cartridge.", price: 189.99, inventory: 27, inventoryStatus: "low_stock", keywords: ["pull down faucet", "kitchen faucet"], specs: { finish: "matte black", material: "brass" }, popularityScore: 86 },
  { id: "prod-hero-013", leafId: "leaf-shop-lights", brand: "BenchBright", title: "BenchBright 4 ft LED Shop Light 2-Pack", shortDescription: "Linkable 4,000 lumen LED shop lights.", longDescription: "Plug-in fixtures with pull chain for garages and workshops.", price: 59.99, inventory: 73, inventoryStatus: "in_stock", keywords: ["shop light", "led shop light"], specs: { length: "4 ft", lumens: 4000 }, popularityScore: 78 },
  { id: "prod-hero-014", leafId: "leaf-led-bulbs", brand: "GlowWorks Bulbs", title: "GlowWorks 60W Equivalent A19 LED Bulb 8-Pack", shortDescription: "800 lumen daylight bulbs with long life rating.", longDescription: "Energy-saving A19 bulbs for lamps and fixtures.", price: 19.99, inventory: 240, inventoryStatus: "in_stock", keywords: ["led bulb", "a19 bulb"], specs: { bulbBase: "E26", colorTemperature: "5000K", lumens: 800 }, popularityScore: 84 },
  { id: "prod-hero-015", leafId: "leaf-breaker-panels", brand: "LoadCenter Pro", title: "LoadCenter Pro 100A Residential Load Center", shortDescription: "100A main breaker panel with 20-space configuration.", longDescription: "Indoor load center for residential electrical upgrades.", price: 189.99, inventory: 14, inventoryStatus: "low_stock", keywords: ["breaker box", "electrical panel"], specs: { amperage: "100A", spaces: 20 }, isContractorGrade: true, popularityScore: 74 },
  { id: "prod-hero-016", leafId: "leaf-extension-cords", brand: "PowerReach Cords", title: "PowerReach 50 ft 12/3 Outdoor Extension Cord", shortDescription: "Heavy-duty outdoor extension cord rated for 15A tools.", longDescription: "Flexible SJTW jacket and lighted end for yard use.", price: 39.99, inventory: 88, inventoryStatus: "in_stock", keywords: ["extension cord", "outdoor extension cord"], specs: { length: "50 ft", gauge: "12/3" }, popularityScore: 81 },
  { id: "prod-hero-017", leafId: "leaf-mulch", brand: "MulchMate", title: "MulchMate Hardwood Mulch 2 cu ft Bag", shortDescription: "Natural hardwood mulch for beds and walkways.", longDescription: "Shredded hardwood mulch helps retain moisture in landscape beds.", price: 4.98, inventory: 520, inventoryStatus: "in_stock", keywords: ["mulch", "landscape mulch"], specs: { bagSize: "2 cu ft", seasonality: "spring" }, isSeasonal: true, popularityScore: 93 },
  { id: "prod-hero-018", leafId: "leaf-pressure-washers", brand: "WashWorks", title: "WashWorks 3100 PSI Gas Pressure Washer", shortDescription: "Gas pressure washer with 25 ft hose and turbo nozzle.", longDescription: "Clean siding, driveways, and decks with quick-connect spray tips.", price: 449.99, inventory: 11, inventoryStatus: "low_stock", keywords: ["pressure washer", "power washer"], specs: { powerSource: "gas", psi: 3100 }, isSeasonal: true, popularityScore: 88 },
  { id: "prod-hero-019", leafId: "leaf-lawn-mowers", brand: "EcoTrim Power", title: "EcoTrim 56V Battery Lawn Mower 21 in", shortDescription: "Self-propelled battery mower with dual-blade deck.", longDescription: "Cut up to 1/2 acre per charge with adjustable height.", price: 549.99, inventory: 19, inventoryStatus: "in_stock", keywords: ["lawn mower", "battery mower"], specs: { powerSource: "battery", cuttingWidth: "21 in" }, isSeasonal: true, popularityScore: 90 },
  { id: "prod-hero-020", leafId: "leaf-smoke-detectors", brand: "SafeHome Detect", title: "SafeHome Smoke & CO Detector 2-Pack", shortDescription: "Combination smoke and carbon monoxide alarms.", longDescription: "Battery backup and voice alerts for whole-home safety.", price: 49.99, inventory: 102, inventoryStatus: "in_stock", keywords: ["smoke detector", "smoke alarm"], specs: { packCount: 2, sensorType: "photoelectric" }, popularityScore: 86 },
  { id: "prod-hero-021", leafId: "leaf-string-trimmers", brand: "TrimLine Garden", title: "TrimLine 40V String Trimmer Kit", shortDescription: "Balanced string trimmer with bump feed head.", longDescription: "Convertible trimmer with adjustable shaft for edging and weed control.", price: 169.99, inventory: 36, inventoryStatus: "in_stock", keywords: ["string trimmer", "weed eater"], specs: { powerSource: "battery", cuttingWidth: "13 in" }, isSeasonal: true, popularityScore: 87 },
  { id: "prod-hero-022", leafId: "leaf-storage-racks", brand: "GarageGrid", title: "GarageGrid Wall-Mounted Storage Rack 48 in", shortDescription: "Heavy-duty wall rack for bins, ladders, and gear.", longDescription: "Powder-coated steel rails and adjustable hooks.", price: 79.99, inventory: 44, inventoryStatus: "in_stock", keywords: ["wall storage rack", "garage storage"], specs: { width: "48 in", capacity: "300 lb" }, popularityScore: 79 },
  { id: "prod-hero-023", leafId: "leaf-smart-thermostats", brand: "ThermoLink", title: "ThermoLink Smart Thermostat with Room Sensors", shortDescription: "Wi-Fi thermostat with app control and geofencing.", longDescription: "Save energy with scheduling and remote sensors.", price: 149.99, inventory: 52, inventoryStatus: "in_stock", keywords: ["smart thermostat"], specs: { connectivity: "Wi-Fi" }, popularityScore: 83 },
  { id: "prod-hero-024", leafId: "leaf-toilet-parts", brand: "SealTight Plumbing", title: "SealTight Universal Toilet Flange Repair Kit", shortDescription: "Stainless repair ring and bolts for wobbly toilets.", longDescription: "Fix rocking toilets and damaged closet flanges.", price: 18.99, inventory: 67, inventoryStatus: "in_stock", keywords: ["toilet flange", "closet flange"], specs: { material: "stainless steel", connectionSize: "3 in" }, popularityScore: 77 },
  { id: "prod-hero-025", leafId: "leaf-drywall", brand: "DrywallDirect", title: "DrywallDirect 1/2 in x 4 ft x 8 ft Drywall Panel", shortDescription: "Standard gypsum board panel for interior walls.", longDescription: "Lightweight panel for remodeling and new construction.", price: 14.98, inventory: 180, inventoryStatus: "in_stock", keywords: ["drywall", "sheetrock"], specs: { thickness: "1/2 in", panelSize: "4 ft x 8 ft" }, isContractorGrade: true, popularityScore: 88 },
  { id: "prod-hero-026", leafId: "leaf-circular-saws", brand: "ProSaw Industrial", title: "ProSaw 7-1/4 in Magnesium Circular Saw", shortDescription: "Lightweight circular saw for framing.", longDescription: "15A motor and electric brake for professional cutting.", price: 159.99, inventory: 22, inventoryStatus: "low_stock", keywords: ["circular saw", "table saw"], specs: { bladeSize: "7-1/4 in", amperage: "15A" }, isContractorGrade: true, popularityScore: 81 },
  { id: "prod-hero-027", leafId: "leaf-insulation", brand: "InsulGuard", title: "InsulGuard R-13 Fiberglass Batt Insulation 15 in", shortDescription: "Pre-cut R-13 batts for 2x4 walls.", longDescription: "Kraft-faced fiberglass batts improve thermal comfort.", price: 54.99, inventory: 64, inventoryStatus: "in_stock", keywords: ["insulation", "r-13 batt"], specs: { rValue: "R-13", width: "15 in" }, isContractorGrade: true, popularityScore: 75 },
  { id: "prod-hero-028", leafId: "leaf-pvc-fittings", brand: "PipeLine Essentials", title: "PipeLine 3 in PVC Elbow Fitting 10-Pack", shortDescription: "Schedule 40 PVC 90-degree elbows for drain lines.", longDescription: "Solvent-weld fittings for DWV applications.", price: 16.99, inventory: 132, inventoryStatus: "in_stock", keywords: ["pvc elbow", "plumbing fitting"], specs: { material: "PVC", connectionSize: "3 in", packCount: 10 }, popularityScore: 70 },
  { id: "prod-hero-029", leafId: "leaf-bath-vanities", brand: "VanityWorks", title: "VanityWorks 30 in Single Sink Bath Vanity", shortDescription: "Shaker-style vanity with cultured marble top.", longDescription: "Soft-close doors and compact footprint for guest baths.", price: 399.99, inventory: 9, inventoryStatus: "low_stock", keywords: ["bath vanity"], specs: { width: "30 in", finish: "white" }, popularityScore: 72 },
  { id: "prod-hero-030", leafId: "leaf-kitchen-sinks", brand: "SinkStone", title: "SinkStone Undermount Stainless Kitchen Sink 33 in", shortDescription: "Deep single-bowl 16-gauge stainless sink.", longDescription: "Sound-dampening pads and rounded corners.", price: 279.99, inventory: 16, inventoryStatus: "in_stock", keywords: ["kitchen sink", "undermount sink"], specs: { width: "33 in", gauge: "16" }, popularityScore: 76 },
  { id: "prod-hero-031", leafId: "leaf-refrigerators", brand: "IceBox Pro", title: "IceBox Pro 25 cu ft French Door Refrigerator", shortDescription: "Stainless French door fridge with ice maker.", longDescription: "Adjustable shelving and humidity-controlled crispers.", price: 2199.99, inventory: 6, inventoryStatus: "low_stock", keywords: ["refrigerator", "french door fridge"], specs: { capacity: "25 cu ft", finish: "stainless" }, popularityScore: 84 },
  { id: "prod-hero-032", leafId: "leaf-portable-ac", brand: "CoolBreeze Portable", title: "CoolBreeze 12,000 BTU Portable Air Conditioner", shortDescription: "Portable AC for rooms up to 450 sq ft.", longDescription: "Rolling chassis, window kit, and remote control.", price: 399.99, inventory: 21, inventoryStatus: "in_stock", keywords: ["portable ac", "air conditioner"], specs: { btu: 12000, coverage: "450 sq ft" }, isSeasonal: true, popularityScore: 80 },
  { id: "prod-hero-033", leafId: "leaf-vinyl-flooring", brand: "PlankHaus Flooring", title: "PlankHaus Waterproof LVP 23.6 sq ft Carton", shortDescription: "Waterproof luxury vinyl plank in Weathered Oak.", longDescription: "Click-lock planks with attached pad.", price: 59.99, inventory: 58, inventoryStatus: "in_stock", keywords: ["lvp", "vinyl plank"], specs: { coverage: "23.6 sq ft", waterproof: true }, popularityScore: 78 },
  { id: "prod-hero-034", leafId: "leaf-exterior-paint", brand: "WeatherShield Coatings", title: "WeatherShield Exterior Acrylic Paint 1 gal", shortDescription: "Fade-resistant exterior paint in Slate Gray.", longDescription: "Flexible coating resists cracking and mildew.", price: 44.99, inventory: 49, inventoryStatus: "in_stock", keywords: ["exterior paint", "house paint"], specs: { containerSize: "1 gal", interiorExterior: "exterior" }, isSeasonal: true, popularityScore: 74 },
  { id: "prod-hero-035", leafId: "leaf-anchors", brand: "QuickMount Hardware", title: "QuickMount Heavy-Duty Toggle Anchors 25-Pack", shortDescription: "Metal toggle anchors for drywall and hollow walls.", longDescription: "Install shelves and mirrors securely in hollow walls.", price: 12.99, inventory: 145, inventoryStatus: "in_stock", keywords: ["toggle anchor", "drywall anchor"], specs: { loadRating: "100 lb", packCount: 25 }, popularityScore: 71 },
  { id: "prod-hero-036", leafId: "leaf-plywood", brand: "PanelCraft", title: "PanelCraft 3/4 in x 4 ft x 8 ft Sanded Plywood", shortDescription: "Sanded plywood panel for shelving and cabinets.", longDescription: "Smooth face veneer suitable for shop projects.", price: 62.99, inventory: 55, inventoryStatus: "in_stock", keywords: ["plywood", "sanded plywood"], specs: { thickness: "3/4 in", panelSize: "4 ft x 8 ft" }, isContractorGrade: true, popularityScore: 73 },
  { id: "prod-hero-037", leafId: "leaf-screwdriver-sets", brand: "DriverDock", title: "DriverDock 20-Piece Screwdriver Set", shortDescription: "Phillips, slotted, and precision screwdrivers.", longDescription: "Color-coded handles and hardened tips.", price: 24.99, inventory: 167, inventoryStatus: "in_stock", keywords: ["screwdriver set"], specs: { pieceCount: 20 }, popularityScore: 69 },
  { id: "prod-hero-038", leafId: "leaf-work-gloves", brand: "TitanGrip", title: "TitanGrip Impact Work Gloves Large", shortDescription: "TPR knuckle protection and touchscreen fingertips.", longDescription: "Breathable back-of-hand protection for construction tasks.", price: 22.99, inventory: 198, inventoryStatus: "in_stock", keywords: ["work gloves"], specs: { size: "L", touchscreen: true }, isContractorGrade: true, popularityScore: 68 },
  { id: "prod-hero-039", leafId: "leaf-safety-glasses", brand: "ClearView Safety", title: "ClearView Anti-Fog Safety Glasses 3-Pack", shortDescription: "ANSI-rated clear safety glasses.", longDescription: "Lightweight wraparound design with anti-fog coating.", price: 14.99, inventory: 221, inventoryStatus: "in_stock", keywords: ["safety glasses"], specs: { packCount: 3, antiFog: true }, popularityScore: 67 },
  { id: "prod-hero-040", leafId: "leaf-cordless-drills", brand: "ProGrade Tools", title: "ProGrade 18V Compact Drill Kit", shortDescription: "Compact drill for tight spaces and home projects.", longDescription: "Includes one battery, charger, and bit holder.", price: 99.99, inventory: 0, inventoryStatus: "out_of_stock", keywords: ["cordless drill", "compact drill"], specs: { voltage: "18V", chuckSize: "3/8 in", includedBatteries: 1 }, popularityScore: 65 },
  { id: "prod-hero-041", leafId: "leaf-interior-paint", brand: "ApexCoat", title: "ApexCoat Cabinet & Trim Enamel 1 qt", shortDescription: "Hard-shell enamel for cabinets and trim.", longDescription: "Smooth leveling formula resists scuffs on trim.", price: 34.99, inventory: 57, inventoryStatus: "in_stock", keywords: ["cabinet paint", "trim paint"], specs: { containerSize: "1 qt", sheen: "Semi-Gloss" }, popularityScore: 71 },
  { id: "prod-hero-042", leafId: "leaf-ceiling-fans", brand: "AirStream Comfort", title: "AirStream 44 in Outdoor Rated Ceiling Fan", shortDescription: "Weather-resistant fan for covered patios.", longDescription: "Stainless hardware and sealed motor for damp locations.", price: 129.99, inventory: 0, inventoryStatus: "out_of_stock", keywords: ["outdoor ceiling fan"], specs: { bladeSpan: "44 in", dampRated: true }, isSeasonal: true, popularityScore: 66 },
  { id: "prod-hero-043", leafId: "leaf-mulch", brand: "GreenHaven Garden", title: "GreenHaven Color-Enhanced Mulch 2 cu ft", shortDescription: "Long-lasting color-enhanced landscape mulch.", longDescription: "Fade-resistant color mulch for front beds.", price: 5.48, inventory: 8, inventoryStatus: "low_stock", keywords: ["colored mulch"], specs: { bagSize: "2 cu ft", color: "brown" }, isSeasonal: true, popularityScore: 70 },
  { id: "prod-hero-044", leafId: "leaf-shop-vacs", brand: "CleanSweep Vac", title: "CleanSweep 6-Gallon Compact Shop Vac", shortDescription: "Portable wet/dry vac for cars and small shops.", longDescription: "Compact tank with onboard hose storage.", price: 69.99, inventory: 0, inventoryStatus: "out_of_stock", keywords: ["shop vac", "compact vacuum"], specs: { tankCapacity: "6 gal" }, popularityScore: 62 },
  { id: "prod-hero-045", leafId: "leaf-impact-drivers", brand: "ForgeLine Impact", title: "ForgeLine 12V Pocket Impact Driver", shortDescription: "Ultra-compact impact for cabinet installers.", longDescription: "Fits in a tool belt pouch for cabinet hardware.", price: 89.99, inventory: 31, inventoryStatus: "in_stock", keywords: ["compact impact driver"], specs: { voltage: "12V" }, popularityScore: 64 },
  { id: "prod-hero-046", leafId: "leaf-extension-cords", brand: "EverVolt", title: "EverVolt 100 ft 14/3 Contractor Extension Cord", shortDescription: "Lighted end contractor cord for job sites.", longDescription: "Flexible cold-weather jacket and molded plugs.", price: 79.99, inventory: 26, inventoryStatus: "in_stock", keywords: ["contractor extension cord"], specs: { length: "100 ft", gauge: "14/3" }, isContractorGrade: true, popularityScore: 73 },
  { id: "prod-hero-047", leafId: "leaf-string-trimmers", brand: "YardForce", title: "YardForce Gas String Trimmer 25 cc", shortDescription: "Gas trimmer with straight shaft for heavy weeds.", longDescription: "Bump-feed head for large yards.", price: 199.99, inventory: 17, inventoryStatus: "in_stock", keywords: ["gas trimmer", "weed eater"], specs: { powerSource: "gas", engineSize: "25 cc" }, isSeasonal: true, popularityScore: 75 },
  { id: "prod-hero-048", leafId: "leaf-gfci-outlets", brand: "SparkSafe", title: "SparkSafe Weather-Resistant GFCI Outlet", shortDescription: "WR GFCI for outdoor and garage locations.", longDescription: "Weather-resistant cover compatibility and LED indicator.", price: 17.99, inventory: 124, inventoryStatus: "in_stock", keywords: ["weather resistant gfci"], specs: { amperage: "20A", weatherResistant: true }, popularityScore: 72 },
  { id: "prod-hero-049", leafId: "leaf-storage-racks", brand: "ShelfLogic", title: "ShelfLogic 5-Tier Boltless Shelving Unit", shortDescription: "72 in tall boltless shelving for garage.", longDescription: "Adjustable shelves assemble without tools.", price: 129.99, inventory: 29, inventoryStatus: "in_stock", keywords: ["shelving unit", "storage shelves"], specs: { height: "72 in", tiers: 5 }, popularityScore: 77 },
  { id: "prod-hero-050", leafId: "leaf-smart-thermostats", brand: "HomePulse Smart", title: "HomePulse Learning Thermostat Pro", shortDescription: "Premium learning thermostat with energy reports.", longDescription: "Learns household patterns and supports multi-zone homes.", price: 229.99, inventory: 18, inventoryStatus: "in_stock", keywords: ["learning thermostat"], specs: { connectivity: "Wi-Fi", learning: true }, popularityScore: 79 },
];

export const VARIANT_FAMILY_TEMPLATES: VariantFamilyTemplate[] = [
  { id: "family-paint-sheen", leafId: "leaf-interior-paint", brand: "TrueCoat Paints", baseTitle: "TrueCoat Interior Paint", description: "Low-VOC acrylic latex interior paint with scrubbable finish.", keywords: ["interior paint", "wall paint"], variants: [
    { suffix: "Eggshell 1 gal Soft White", specs: { sheen: "Eggshell", containerSize: "1 gal", colorFamily: "Soft White" }, priceMultiplier: 1, inventoryWeight: 3 },
    { suffix: "Satin 1 gal Soft White", specs: { sheen: "Satin", containerSize: "1 gal", colorFamily: "Soft White" }, priceMultiplier: 1.05, inventoryWeight: 2 },
    { suffix: "Eggshell 5 gal Soft White", specs: { sheen: "Eggshell", containerSize: "5 gal", colorFamily: "Soft White" }, priceMultiplier: 4.6, inventoryWeight: 1 },
  ] },
  { id: "family-ceiling-fan-finish", leafId: "leaf-ceiling-fans", brand: "BrightSpan Lighting", baseTitle: "BrightSpan 52 in Ceiling Fan", description: "Quiet reversible motor ceiling fan with light kit.", keywords: ["ceiling fan"], variants: [
    { suffix: "Brushed Nickel", specs: { bladeSpan: "52 in", finish: "brushed nickel" }, priceMultiplier: 1, inventoryWeight: 2 },
    { suffix: "Matte Black", specs: { bladeSpan: "52 in", finish: "matte black" }, priceMultiplier: 1.02, inventoryWeight: 2 },
    { suffix: "White", specs: { bladeSpan: "52 in", finish: "white" }, priceMultiplier: 0.98, inventoryWeight: 1 },
  ] },
  { id: "family-led-bulb-temp", leafId: "leaf-led-bulbs", brand: "LumenPath", baseTitle: "LumenPath 60W Equivalent A19 LED Bulb 4-Pack", description: "Energy-efficient LED bulbs for household fixtures.", keywords: ["led bulb"], variants: [
    { suffix: "5000K Daylight", specs: { colorTemperature: "5000K", lumens: 800 }, priceMultiplier: 1, inventoryWeight: 3 },
    { suffix: "3000K Soft White", specs: { colorTemperature: "3000K", lumens: 800 }, priceMultiplier: 1, inventoryWeight: 3 },
    { suffix: "2700K Warm White", specs: { colorTemperature: "2700K", lumens: 800 }, priceMultiplier: 0.98, inventoryWeight: 2 },
  ] },
  { id: "family-lumber-length", leafId: "leaf-dimension-lumber", brand: "TimberCore", baseTitle: "TimberCore 2 in x 4 in Pressure-Treated Lumber", description: "Ground-contact rated pressure-treated framing lumber.", keywords: ["2x4", "pressure treated"], variants: [
    { suffix: "8 ft", specs: { length: "8 ft", pressureTreated: true }, priceMultiplier: 1, inventoryWeight: 4 },
    { suffix: "10 ft", specs: { length: "10 ft", pressureTreated: true }, priceMultiplier: 1.25, inventoryWeight: 2 },
    { suffix: "12 ft", specs: { length: "12 ft", pressureTreated: true }, priceMultiplier: 1.5, inventoryWeight: 1 },
  ] },
  { id: "family-faucet-finish", leafId: "leaf-kitchen-faucets", brand: "CopperCreek Plumbing", baseTitle: "CopperCreek Pull-Down Kitchen Faucet", description: "Single-handle kitchen faucet with pull-down sprayer.", keywords: ["kitchen faucet"], variants: [
    { suffix: "Chrome", specs: { finish: "chrome" }, priceMultiplier: 1, inventoryWeight: 2 },
    { suffix: "Matte Black", specs: { finish: "matte black" }, priceMultiplier: 1.08, inventoryWeight: 2 },
    { suffix: "Stainless", specs: { finish: "stainless" }, priceMultiplier: 1.04, inventoryWeight: 1 },
  ] },
  { id: "family-mulch-size", leafId: "leaf-mulch", brand: "OakRiver", baseTitle: "OakRiver Hardwood Mulch", description: "Shredded hardwood mulch for landscape beds.", keywords: ["mulch"], variants: [
    { suffix: "1 cu ft Bag", specs: { bagSize: "1 cu ft" }, priceMultiplier: 0.55, inventoryWeight: 3 },
    { suffix: "2 cu ft Bag", specs: { bagSize: "2 cu ft" }, priceMultiplier: 1, inventoryWeight: 4 },
    { suffix: "3 cu ft Bag", specs: { bagSize: "3 cu ft" }, priceMultiplier: 1.35, inventoryWeight: 2 },
  ] },
  { id: "family-drill-batteries", leafId: "leaf-cordless-drills", brand: "RapidDrive Tools", baseTitle: "RapidDrive 20V Cordless Drill Kit", description: "Brushless drill kit for home and light professional use.", keywords: ["cordless drill"], variants: [
    { suffix: "1-Battery Kit", specs: { includedBatteries: 1, voltage: "20V" }, priceMultiplier: 1, inventoryWeight: 3 },
    { suffix: "2-Battery Kit", specs: { includedBatteries: 2, voltage: "20V" }, priceMultiplier: 1.35, inventoryWeight: 2 },
  ] },
  { id: "family-storage-width", leafId: "leaf-storage-racks", brand: "Zenith Workshop", baseTitle: "Zenith Wall Storage Rail System", description: "Modular wall rail storage for garages.", keywords: ["wall storage"], variants: [
    { suffix: "36 in Rail Kit", specs: { width: "36 in" }, priceMultiplier: 0.85, inventoryWeight: 2 },
    { suffix: "48 in Rail Kit", specs: { width: "48 in" }, priceMultiplier: 1, inventoryWeight: 2 },
    { suffix: "64 in Rail Kit", specs: { width: "64 in" }, priceMultiplier: 1.2, inventoryWeight: 1 },
  ] },
];

export function getHeroTemplateById(id: string): HeroProductTemplate | undefined {
  return HERO_PRODUCT_TEMPLATES.find((hero) => hero.id === id);
}
