import type { MerchandisingRule } from "@retailer-search/shared-types";

export interface SynonymGroup {
  terms: [string, string];
}

export const DEMO_SYNONYM_GROUPS: SynonymGroup[] = [
  { terms: ["shop vac", "wet dry vacuum"] },
  { terms: ["weed eater", "string trimmer"] },
  { terms: ["angle grinder", "grinder"] },
  { terms: ["breaker box", "electrical panel"] },
  { terms: ["sheetrock", "drywall"] },
  { terms: ["caulk", "sealant"] },
  { terms: ["extension cord", "power cord"] },
  { terms: ["socket set", "mechanics set"] },
  { terms: ["ac unit", "air conditioner"] },
  { terms: ["lawn mower", "mower"] },
  { terms: ["impact driver", "impact drill"] },
  { terms: ["gfci outlet", "ground fault outlet"] },
  { terms: ["pressure washer", "power washer"] },
  { terms: ["stud finder", "wall scanner"] },
  { terms: ["paint sprayer", "spray gun"] },
  { terms: ["smoke detector", "smoke alarm"] },
  { terms: ["pull down faucet", "pull-down faucet"] },
  { terms: ["shop light", "work light"] },
  { terms: ["mulch", "landscape mulch"] },
  { terms: ["drywall screws", "sheetrock screws"] },
  { terms: ["cordless drill", "battery drill"] },
  { terms: ["ceiling fan", "overhead fan"] },
  { terms: ["primer", "sealer primer"] },
  { terms: ["toilet flange", "closet flange"] },
  { terms: ["table saw", "bench saw"] },
];

export const DEMO_TYPO_CORRECTIONS: Record<string, string> = {
  dril: "drill",
  "cieling fan": "ceiling fan",
  "water heeter": "water heater",
  "extenstion cord": "extension cord",
  "pain sprayer": "paint sprayer",
  hammr: "hammer",
  mulhc: "mulch",
  "gfic outlet": "gfci outlet",
  "presure washer": "pressure washer",
  "weed eatr": "weed eater",
  "drywll screws": "drywall screws",
  "shop vav": "shop vac",
  "smoke detecter": "smoke detector",
  "extention cord": "extension cord",
  "ceilng fan": "ceiling fan",
  "cordles drill": "cordless drill",
  "primr": "primer",
};

export const DEMO_ZERO_RESULT_FALLBACKS: Record<string, string> = {
  "sheet rock mud": "drywall compound",
  "hose bib": "outdoor faucet",
  "weed eater line": "trimmer line",
  "outlet cover plate": "wall plate",
  "breaker switch": "circuit breaker",
  "fan blade arm": "ceiling fan blade",
  "wood putty stick": "wood filler",
  "pipe dope": "thread sealant",
  "outdoor plug cover": "weatherproof outlet cover",
  "garage wall hook": "storage hook",
};

export function buildSynonymMap(): Record<string, string> {
  const map: Record<string, string> = {};
  for (const group of DEMO_SYNONYM_GROUPS) {
    const [left, right] = group.terms;
    map[left] = right;
    map[right] = left;
  }
  return map;
}

export function buildDemoMerchandisingRules(): MerchandisingRule[] {
  return [
    {
      id: "rule-demo-pin-cordless-drill",
      name: "Pin hero cordless drill combo for cordless drill searches",
      active: true,
      priority: 120,
      action: "pin",
      condition: { query: "cordless drill" },
      productIds: ["prod-hero-001"],
    },
    {
      id: "rule-demo-boost-instock-drills",
      name: "Boost in-stock drills for drill searches",
      active: true,
      priority: 110,
      action: "boost",
      condition: { query: "drill", inStock: true },
      boostAmount: 35,
    },
    {
      id: "rule-demo-bury-oos-mulch",
      name: "Bury out-of-stock mulch for mulch searches",
      active: true,
      priority: 105,
      action: "bury",
      condition: { query: "mulch", inStock: false },
      buryAmount: 40,
    },
    {
      id: "rule-demo-boost-contractor-table-saw",
      name: "Boost contractor-grade table saw results",
      active: true,
      priority: 100,
      action: "boost",
      condition: { query: "table saw" },
      brand: "ProSaw Industrial",
      boostAmount: 30,
    },
    {
      id: "rule-demo-boost-seasonal-lawn",
      name: "Boost seasonal lawn products for mower searches",
      active: true,
      priority: 95,
      action: "boost",
      condition: { query: "mower", category: "Outdoor Power Equipment" },
      boostAmount: 25,
    },
    {
      id: "rule-demo-boost-ceiling-fan",
      name: "Boost ceiling fan category for fan searches",
      active: true,
      priority: 90,
      action: "boost",
      condition: { query: "ceiling fan", category: "Lighting & Ceiling Fans" },
      boostAmount: 28,
    },
    {
      id: "rule-demo-bury-oos-shop-vac",
      name: "Bury out-of-stock shop vacs",
      active: true,
      priority: 88,
      action: "bury",
      condition: { query: "shop vac", inStock: false },
      buryAmount: 35,
    },
    {
      id: "rule-demo-boost-gfci",
      name: "Boost GFCI outlet pack for outlet searches",
      active: true,
      priority: 85,
      action: "boost",
      condition: { query: "gfci" },
      productIds: ["prod-hero-008"],
      boostAmount: 32,
    },
    {
      id: "rule-demo-boost-pressure-washer",
      name: "Boost pressure washer hero SKU",
      active: true,
      priority: 82,
      action: "pin",
      condition: { query: "pressure washer" },
      productIds: ["prod-hero-018"],
    },
    {
      id: "rule-demo-boost-string-trimmer",
      name: "Boost string trimmer for weed eater searches",
      active: true,
      priority: 80,
      action: "boost",
      condition: { query: "weed" },
      category: "Outdoor Power Equipment",
      boostAmount: 22,
    },
    {
      id: "rule-demo-boost-drywall-screws",
      name: "Boost drywall screws in fastener searches",
      active: true,
      priority: 78,
      action: "boost",
      condition: { query: "drywall screws" },
      boostAmount: 24,
    },
    {
      id: "rule-demo-bury-clearance-paint",
      name: "Bury premium paint on clearance paint searches",
      active: true,
      priority: 70,
      action: "bury",
      condition: { query: "clearance paint" },
      buryAmount: 20,
    },
    {
      id: "rule-demo-boost-primer",
      name: "Boost primer hero for primer searches",
      active: true,
      priority: 68,
      action: "boost",
      condition: { query: "primer" },
      productIds: ["prod-hero-011"],
      boostAmount: 26,
    },
    {
      id: "rule-demo-boost-smoke-detector",
      name: "Boost smoke detector pack",
      active: true,
      priority: 65,
      action: "boost",
      condition: { query: "smoke detector" },
      productIds: ["prod-hero-020"],
      boostAmount: 30,
    },
    {
      id: "rule-demo-boost-plumbing-flange",
      name: "Boost toilet flange repair kits",
      active: true,
      priority: 62,
      action: "boost",
      condition: { query: "toilet flange" },
      boostAmount: 18,
    },
    {
      id: "rule-demo-boost-extension-cord",
      name: "Boost outdoor extension cords",
      active: true,
      priority: 60,
      action: "boost",
      condition: { query: "extension cord" },
      category: "Electrical",
      boostAmount: 20,
    },
    {
      id: "rule-demo-boost-summit-electric",
      name: "Boost Summit Electric for electrical panel searches",
      active: true,
      priority: 58,
      action: "boost",
      condition: { query: "breaker box" },
      brand: "Summit Electric",
      boostAmount: 22,
    },
    {
      id: "rule-demo-hide-oos-fans",
      name: "Hide out-of-stock ceiling fans",
      active: true,
      priority: 55,
      action: "hide",
      condition: { query: "ceiling fan", inStock: false },
    },
    {
      id: "rule-demo-default-instock-boost",
      name: "Default in-stock boost",
      active: true,
      priority: 10,
      action: "boost",
      condition: { inStock: true },
      boostAmount: 5,
    },
    {
      id: "rule-demo-bury-oos-default",
      name: "Bury out-of-stock items by default",
      active: true,
      priority: 5,
      action: "bury",
      condition: { inStock: false },
      buryAmount: 15,
    },
  ];
}
